// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kfMessage.proto

package com.ty.chat.protocol;

public interface KfForwardMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.KfForwardMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .protocol.Command cmd = 1;</code>
   * @return Whether the cmd field is set.
   */
  boolean hasCmd();
  /**
   * <code>optional .protocol.Command cmd = 1;</code>
   * @return The cmd.
   */
  com.ty.chat.protocol.Command getCmd();

  /**
   * <code>required string appKey = 2;</code>
   * @return Whether the appKey field is set.
   */
  boolean hasAppKey();
  /**
   * <code>required string appKey = 2;</code>
   * @return The appKey.
   */
  java.lang.String getAppKey();
  /**
   * <code>required string appKey = 2;</code>
   * @return The bytes for appKey.
   */
  com.google.protobuf.ByteString
      getAppKeyBytes();

  /**
   * <code>optional string toId = 3;</code>
   * @return Whether the toId field is set.
   */
  boolean hasToId();
  /**
   * <code>optional string toId = 3;</code>
   * @return The toId.
   */
  java.lang.String getToId();
  /**
   * <code>optional string toId = 3;</code>
   * @return The bytes for toId.
   */
  com.google.protobuf.ByteString
      getToIdBytes();

  /**
   * <code>optional .protocol.KfSend kfSend = 4;</code>
   * @return Whether the kfSend field is set.
   */
  boolean hasKfSend();
  /**
   * <code>optional .protocol.KfSend kfSend = 4;</code>
   * @return The kfSend.
   */
  com.ty.chat.protocol.KfSend getKfSend();
  /**
   * <code>optional .protocol.KfSend kfSend = 4;</code>
   */
  com.ty.chat.protocol.KfSendOrBuilder getKfSendOrBuilder();

  /**
   * <code>optional .protocol.KfIsReaded kfIsReaded = 5;</code>
   * @return Whether the kfIsReaded field is set.
   */
  boolean hasKfIsReaded();
  /**
   * <code>optional .protocol.KfIsReaded kfIsReaded = 5;</code>
   * @return The kfIsReaded.
   */
  com.ty.chat.protocol.KfIsReaded getKfIsReaded();
  /**
   * <code>optional .protocol.KfIsReaded kfIsReaded = 5;</code>
   */
  com.ty.chat.protocol.KfIsReadedOrBuilder getKfIsReadedOrBuilder();

  /**
   * <code>optional .protocol.KfAckAndCancel kfAckAndCancel = 6;</code>
   * @return Whether the kfAckAndCancel field is set.
   */
  boolean hasKfAckAndCancel();
  /**
   * <code>optional .protocol.KfAckAndCancel kfAckAndCancel = 6;</code>
   * @return The kfAckAndCancel.
   */
  com.ty.chat.protocol.KfAckAndCancel getKfAckAndCancel();
  /**
   * <code>optional .protocol.KfAckAndCancel kfAckAndCancel = 6;</code>
   */
  com.ty.chat.protocol.KfAckAndCancelOrBuilder getKfAckAndCancelOrBuilder();

  /**
   * <code>optional .protocol.KfWithdraw kfWithdraw = 7;</code>
   * @return Whether the kfWithdraw field is set.
   */
  boolean hasKfWithdraw();
  /**
   * <code>optional .protocol.KfWithdraw kfWithdraw = 7;</code>
   * @return The kfWithdraw.
   */
  com.ty.chat.protocol.KfWithdraw getKfWithdraw();
  /**
   * <code>optional .protocol.KfWithdraw kfWithdraw = 7;</code>
   */
  com.ty.chat.protocol.KfWithdrawOrBuilder getKfWithdrawOrBuilder();

  /**
   * <code>optional .protocol.KfMessageResp kfMessageResp = 8;</code>
   * @return Whether the kfMessageResp field is set.
   */
  boolean hasKfMessageResp();
  /**
   * <code>optional .protocol.KfMessageResp kfMessageResp = 8;</code>
   * @return The kfMessageResp.
   */
  com.ty.chat.protocol.KfMessageResp getKfMessageResp();
  /**
   * <code>optional .protocol.KfMessageResp kfMessageResp = 8;</code>
   */
  com.ty.chat.protocol.KfMessageRespOrBuilder getKfMessageRespOrBuilder();

  /**
   * <code>optional .protocol.KfSession kfSession = 9;</code>
   * @return Whether the kfSession field is set.
   */
  boolean hasKfSession();
  /**
   * <code>optional .protocol.KfSession kfSession = 9;</code>
   * @return The kfSession.
   */
  com.ty.chat.protocol.KfSession getKfSession();
  /**
   * <code>optional .protocol.KfSession kfSession = 9;</code>
   */
  com.ty.chat.protocol.KfSessionOrBuilder getKfSessionOrBuilder();
}
