// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kfMessage.proto

package com.ty.chat.protocol;

public interface KfHeartbeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.KfHeartbeat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>required int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>required int32 ack = 2;</code>
   * @return Whether the ack field is set.
   */
  boolean hasAck();
  /**
   * <code>required int32 ack = 2;</code>
   * @return The ack.
   */
  int getAck();
}
