// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kfMessage.proto

package com.ty.chat.protocol;

public interface KfIsReadedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.KfIsReaded)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 未读消息id 已逗号隔开
   * </pre>
   *
   * <code>required string ids = 1;</code>
   * @return Whether the ids field is set.
   */
  boolean hasIds();
  /**
   * <pre>
   * 未读消息id 已逗号隔开
   * </pre>
   *
   * <code>required string ids = 1;</code>
   * @return The ids.
   */
  java.lang.String getIds();
  /**
   * <pre>
   * 未读消息id 已逗号隔开
   * </pre>
   *
   * <code>required string ids = 1;</code>
   * @return The bytes for ids.
   */
  com.google.protobuf.ByteString
      getIdsBytes();

  /**
   * <code>required string sessionId = 2;</code>
   * @return Whether the sessionId field is set.
   */
  boolean hasSessionId();
  /**
   * <code>required string sessionId = 2;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>required string sessionId = 2;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();
}
