// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kfMessage.proto

package com.ty.chat.protocol;

/**
 * <pre>
 * 总的消息 13
 * </pre>
 *
 * Protobuf type {@code protocol.KfMessage}
 */
public  final class KfMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.KfMessage)
    KfMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KfMessage.newBuilder() to construct.
  private KfMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KfMessage() {
    cmd_ = 0;
    version_ = "1.0.0";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new KfMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private KfMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            com.ty.chat.protocol.Command value = com.ty.chat.protocol.Command.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              cmd_ = rawValue;
            }
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            version_ = bs;
            break;
          }
          case 26: {
            com.ty.chat.protocol.KfReq.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) != 0)) {
              subBuilder = kfReq_.toBuilder();
            }
            kfReq_ = input.readMessage(com.ty.chat.protocol.KfReq.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(kfReq_);
              kfReq_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          case 34: {
            com.ty.chat.protocol.KfSend.Builder subBuilder = null;
            if (((bitField0_ & 0x00000008) != 0)) {
              subBuilder = kfSend_.toBuilder();
            }
            kfSend_ = input.readMessage(com.ty.chat.protocol.KfSend.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(kfSend_);
              kfSend_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000008;
            break;
          }
          case 42: {
            com.ty.chat.protocol.KfIsReaded.Builder subBuilder = null;
            if (((bitField0_ & 0x00000010) != 0)) {
              subBuilder = kfIsReaded_.toBuilder();
            }
            kfIsReaded_ = input.readMessage(com.ty.chat.protocol.KfIsReaded.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(kfIsReaded_);
              kfIsReaded_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000010;
            break;
          }
          case 50: {
            com.ty.chat.protocol.KfAckAndCancel.Builder subBuilder = null;
            if (((bitField0_ & 0x00000020) != 0)) {
              subBuilder = kfAckAndCancel_.toBuilder();
            }
            kfAckAndCancel_ = input.readMessage(com.ty.chat.protocol.KfAckAndCancel.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(kfAckAndCancel_);
              kfAckAndCancel_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000020;
            break;
          }
          case 58: {
            com.ty.chat.protocol.KfWithdraw.Builder subBuilder = null;
            if (((bitField0_ & 0x00000040) != 0)) {
              subBuilder = kfWithdraw_.toBuilder();
            }
            kfWithdraw_ = input.readMessage(com.ty.chat.protocol.KfWithdraw.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(kfWithdraw_);
              kfWithdraw_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000040;
            break;
          }
          case 66: {
            com.ty.chat.protocol.KfHeartbeat.Builder subBuilder = null;
            if (((bitField0_ & 0x00000080) != 0)) {
              subBuilder = kfHeartbeat_.toBuilder();
            }
            kfHeartbeat_ = input.readMessage(com.ty.chat.protocol.KfHeartbeat.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(kfHeartbeat_);
              kfHeartbeat_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000080;
            break;
          }
          case 74: {
            com.ty.chat.protocol.KfSession.Builder subBuilder = null;
            if (((bitField0_ & 0x00000100) != 0)) {
              subBuilder = kfSession_.toBuilder();
            }
            kfSession_ = input.readMessage(com.ty.chat.protocol.KfSession.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(kfSession_);
              kfSession_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000100;
            break;
          }
          case 82: {
            com.ty.chat.protocol.KfMessageResp.Builder subBuilder = null;
            if (((bitField0_ & 0x00000200) != 0)) {
              subBuilder = kfMessageResp_.toBuilder();
            }
            kfMessageResp_ = input.readMessage(com.ty.chat.protocol.KfMessageResp.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(kfMessageResp_);
              kfMessageResp_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000200;
            break;
          }
          case 90: {
            com.ty.chat.protocol.KfUnendMsg.Builder subBuilder = null;
            if (((bitField0_ & 0x00000400) != 0)) {
              subBuilder = kfUnendMsg_.toBuilder();
            }
            kfUnendMsg_ = input.readMessage(com.ty.chat.protocol.KfUnendMsg.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(kfUnendMsg_);
              kfUnendMsg_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000400;
            break;
          }
          case 98: {
            com.ty.chat.protocol.KfOnline.Builder subBuilder = null;
            if (((bitField0_ & 0x00000800) != 0)) {
              subBuilder = kfOnline_.toBuilder();
            }
            kfOnline_ = input.readMessage(com.ty.chat.protocol.KfOnline.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(kfOnline_);
              kfOnline_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000800;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ty.chat.protocol.KfMessageOuterClass.internal_static_protocol_KfMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ty.chat.protocol.KfMessageOuterClass.internal_static_protocol_KfMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ty.chat.protocol.KfMessage.class, com.ty.chat.protocol.KfMessage.Builder.class);
  }

  private int bitField0_;
  public static final int CMD_FIELD_NUMBER = 1;
  private int cmd_;
  /**
   * <code>required .protocol.Command cmd = 1;</code>
   * @return Whether the cmd field is set.
   */
  public boolean hasCmd() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required .protocol.Command cmd = 1;</code>
   * @return The cmd.
   */
  public com.ty.chat.protocol.Command getCmd() {
    @SuppressWarnings("deprecation")
    com.ty.chat.protocol.Command result = com.ty.chat.protocol.Command.valueOf(cmd_);
    return result == null ? com.ty.chat.protocol.Command.COMMAND_UNKNOW : result;
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private volatile java.lang.Object version_;
  /**
   * <pre>
   * 版本信息
   * </pre>
   *
   * <code>optional string version = 2 [default = "1.0.0"];</code>
   * @return Whether the version field is set.
   */
  public boolean hasVersion() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 版本信息
   * </pre>
   *
   * <code>optional string version = 2 [default = "1.0.0"];</code>
   * @return The version.
   */
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        version_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * 版本信息
   * </pre>
   *
   * <code>optional string version = 2 [default = "1.0.0"];</code>
   * @return The bytes for version.
   */
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KFREQ_FIELD_NUMBER = 3;
  private com.ty.chat.protocol.KfReq kfReq_;
  /**
   * <code>optional .protocol.KfReq kfReq = 3;</code>
   * @return Whether the kfReq field is set.
   */
  public boolean hasKfReq() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .protocol.KfReq kfReq = 3;</code>
   * @return The kfReq.
   */
  public com.ty.chat.protocol.KfReq getKfReq() {
    return kfReq_ == null ? com.ty.chat.protocol.KfReq.getDefaultInstance() : kfReq_;
  }
  /**
   * <code>optional .protocol.KfReq kfReq = 3;</code>
   */
  public com.ty.chat.protocol.KfReqOrBuilder getKfReqOrBuilder() {
    return kfReq_ == null ? com.ty.chat.protocol.KfReq.getDefaultInstance() : kfReq_;
  }

  public static final int KFSEND_FIELD_NUMBER = 4;
  private com.ty.chat.protocol.KfSend kfSend_;
  /**
   * <code>optional .protocol.KfSend kfSend = 4;</code>
   * @return Whether the kfSend field is set.
   */
  public boolean hasKfSend() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .protocol.KfSend kfSend = 4;</code>
   * @return The kfSend.
   */
  public com.ty.chat.protocol.KfSend getKfSend() {
    return kfSend_ == null ? com.ty.chat.protocol.KfSend.getDefaultInstance() : kfSend_;
  }
  /**
   * <code>optional .protocol.KfSend kfSend = 4;</code>
   */
  public com.ty.chat.protocol.KfSendOrBuilder getKfSendOrBuilder() {
    return kfSend_ == null ? com.ty.chat.protocol.KfSend.getDefaultInstance() : kfSend_;
  }

  public static final int KFISREADED_FIELD_NUMBER = 5;
  private com.ty.chat.protocol.KfIsReaded kfIsReaded_;
  /**
   * <code>optional .protocol.KfIsReaded kfIsReaded = 5;</code>
   * @return Whether the kfIsReaded field is set.
   */
  public boolean hasKfIsReaded() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .protocol.KfIsReaded kfIsReaded = 5;</code>
   * @return The kfIsReaded.
   */
  public com.ty.chat.protocol.KfIsReaded getKfIsReaded() {
    return kfIsReaded_ == null ? com.ty.chat.protocol.KfIsReaded.getDefaultInstance() : kfIsReaded_;
  }
  /**
   * <code>optional .protocol.KfIsReaded kfIsReaded = 5;</code>
   */
  public com.ty.chat.protocol.KfIsReadedOrBuilder getKfIsReadedOrBuilder() {
    return kfIsReaded_ == null ? com.ty.chat.protocol.KfIsReaded.getDefaultInstance() : kfIsReaded_;
  }

  public static final int KFACKANDCANCEL_FIELD_NUMBER = 6;
  private com.ty.chat.protocol.KfAckAndCancel kfAckAndCancel_;
  /**
   * <code>optional .protocol.KfAckAndCancel kfAckAndCancel = 6;</code>
   * @return Whether the kfAckAndCancel field is set.
   */
  public boolean hasKfAckAndCancel() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional .protocol.KfAckAndCancel kfAckAndCancel = 6;</code>
   * @return The kfAckAndCancel.
   */
  public com.ty.chat.protocol.KfAckAndCancel getKfAckAndCancel() {
    return kfAckAndCancel_ == null ? com.ty.chat.protocol.KfAckAndCancel.getDefaultInstance() : kfAckAndCancel_;
  }
  /**
   * <code>optional .protocol.KfAckAndCancel kfAckAndCancel = 6;</code>
   */
  public com.ty.chat.protocol.KfAckAndCancelOrBuilder getKfAckAndCancelOrBuilder() {
    return kfAckAndCancel_ == null ? com.ty.chat.protocol.KfAckAndCancel.getDefaultInstance() : kfAckAndCancel_;
  }

  public static final int KFWITHDRAW_FIELD_NUMBER = 7;
  private com.ty.chat.protocol.KfWithdraw kfWithdraw_;
  /**
   * <code>optional .protocol.KfWithdraw kfWithdraw = 7;</code>
   * @return Whether the kfWithdraw field is set.
   */
  public boolean hasKfWithdraw() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional .protocol.KfWithdraw kfWithdraw = 7;</code>
   * @return The kfWithdraw.
   */
  public com.ty.chat.protocol.KfWithdraw getKfWithdraw() {
    return kfWithdraw_ == null ? com.ty.chat.protocol.KfWithdraw.getDefaultInstance() : kfWithdraw_;
  }
  /**
   * <code>optional .protocol.KfWithdraw kfWithdraw = 7;</code>
   */
  public com.ty.chat.protocol.KfWithdrawOrBuilder getKfWithdrawOrBuilder() {
    return kfWithdraw_ == null ? com.ty.chat.protocol.KfWithdraw.getDefaultInstance() : kfWithdraw_;
  }

  public static final int KFHEARTBEAT_FIELD_NUMBER = 8;
  private com.ty.chat.protocol.KfHeartbeat kfHeartbeat_;
  /**
   * <code>optional .protocol.KfHeartbeat kfHeartbeat = 8;</code>
   * @return Whether the kfHeartbeat field is set.
   */
  public boolean hasKfHeartbeat() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional .protocol.KfHeartbeat kfHeartbeat = 8;</code>
   * @return The kfHeartbeat.
   */
  public com.ty.chat.protocol.KfHeartbeat getKfHeartbeat() {
    return kfHeartbeat_ == null ? com.ty.chat.protocol.KfHeartbeat.getDefaultInstance() : kfHeartbeat_;
  }
  /**
   * <code>optional .protocol.KfHeartbeat kfHeartbeat = 8;</code>
   */
  public com.ty.chat.protocol.KfHeartbeatOrBuilder getKfHeartbeatOrBuilder() {
    return kfHeartbeat_ == null ? com.ty.chat.protocol.KfHeartbeat.getDefaultInstance() : kfHeartbeat_;
  }

  public static final int KFSESSION_FIELD_NUMBER = 9;
  private com.ty.chat.protocol.KfSession kfSession_;
  /**
   * <code>optional .protocol.KfSession kfSession = 9;</code>
   * @return Whether the kfSession field is set.
   */
  public boolean hasKfSession() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional .protocol.KfSession kfSession = 9;</code>
   * @return The kfSession.
   */
  public com.ty.chat.protocol.KfSession getKfSession() {
    return kfSession_ == null ? com.ty.chat.protocol.KfSession.getDefaultInstance() : kfSession_;
  }
  /**
   * <code>optional .protocol.KfSession kfSession = 9;</code>
   */
  public com.ty.chat.protocol.KfSessionOrBuilder getKfSessionOrBuilder() {
    return kfSession_ == null ? com.ty.chat.protocol.KfSession.getDefaultInstance() : kfSession_;
  }

  public static final int KFMESSAGERESP_FIELD_NUMBER = 10;
  private com.ty.chat.protocol.KfMessageResp kfMessageResp_;
  /**
   * <code>optional .protocol.KfMessageResp kfMessageResp = 10;</code>
   * @return Whether the kfMessageResp field is set.
   */
  public boolean hasKfMessageResp() {
    return ((bitField0_ & 0x00000200) != 0);
  }
  /**
   * <code>optional .protocol.KfMessageResp kfMessageResp = 10;</code>
   * @return The kfMessageResp.
   */
  public com.ty.chat.protocol.KfMessageResp getKfMessageResp() {
    return kfMessageResp_ == null ? com.ty.chat.protocol.KfMessageResp.getDefaultInstance() : kfMessageResp_;
  }
  /**
   * <code>optional .protocol.KfMessageResp kfMessageResp = 10;</code>
   */
  public com.ty.chat.protocol.KfMessageRespOrBuilder getKfMessageRespOrBuilder() {
    return kfMessageResp_ == null ? com.ty.chat.protocol.KfMessageResp.getDefaultInstance() : kfMessageResp_;
  }

  public static final int KFUNENDMSG_FIELD_NUMBER = 11;
  private com.ty.chat.protocol.KfUnendMsg kfUnendMsg_;
  /**
   * <code>optional .protocol.KfUnendMsg kfUnendMsg = 11;</code>
   * @return Whether the kfUnendMsg field is set.
   */
  public boolean hasKfUnendMsg() {
    return ((bitField0_ & 0x00000400) != 0);
  }
  /**
   * <code>optional .protocol.KfUnendMsg kfUnendMsg = 11;</code>
   * @return The kfUnendMsg.
   */
  public com.ty.chat.protocol.KfUnendMsg getKfUnendMsg() {
    return kfUnendMsg_ == null ? com.ty.chat.protocol.KfUnendMsg.getDefaultInstance() : kfUnendMsg_;
  }
  /**
   * <code>optional .protocol.KfUnendMsg kfUnendMsg = 11;</code>
   */
  public com.ty.chat.protocol.KfUnendMsgOrBuilder getKfUnendMsgOrBuilder() {
    return kfUnendMsg_ == null ? com.ty.chat.protocol.KfUnendMsg.getDefaultInstance() : kfUnendMsg_;
  }

  public static final int KFONLINE_FIELD_NUMBER = 12;
  private com.ty.chat.protocol.KfOnline kfOnline_;
  /**
   * <code>optional .protocol.KfOnline kfOnline = 12;</code>
   * @return Whether the kfOnline field is set.
   */
  public boolean hasKfOnline() {
    return ((bitField0_ & 0x00000800) != 0);
  }
  /**
   * <code>optional .protocol.KfOnline kfOnline = 12;</code>
   * @return The kfOnline.
   */
  public com.ty.chat.protocol.KfOnline getKfOnline() {
    return kfOnline_ == null ? com.ty.chat.protocol.KfOnline.getDefaultInstance() : kfOnline_;
  }
  /**
   * <code>optional .protocol.KfOnline kfOnline = 12;</code>
   */
  public com.ty.chat.protocol.KfOnlineOrBuilder getKfOnlineOrBuilder() {
    return kfOnline_ == null ? com.ty.chat.protocol.KfOnline.getDefaultInstance() : kfOnline_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasCmd()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (hasKfReq()) {
      if (!getKfReq().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasKfSend()) {
      if (!getKfSend().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasKfIsReaded()) {
      if (!getKfIsReaded().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasKfAckAndCancel()) {
      if (!getKfAckAndCancel().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasKfWithdraw()) {
      if (!getKfWithdraw().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasKfHeartbeat()) {
      if (!getKfHeartbeat().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasKfSession()) {
      if (!getKfSession().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasKfUnendMsg()) {
      if (!getKfUnendMsg().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasKfOnline()) {
      if (!getKfOnline().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, cmd_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getKfReq());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getKfSend());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(5, getKfIsReaded());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(6, getKfAckAndCancel());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeMessage(7, getKfWithdraw());
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeMessage(8, getKfHeartbeat());
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      output.writeMessage(9, getKfSession());
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      output.writeMessage(10, getKfMessageResp());
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      output.writeMessage(11, getKfUnendMsg());
    }
    if (((bitField0_ & 0x00000800) != 0)) {
      output.writeMessage(12, getKfOnline());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, cmd_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getKfReq());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getKfSend());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getKfIsReaded());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getKfAckAndCancel());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getKfWithdraw());
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getKfHeartbeat());
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getKfSession());
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getKfMessageResp());
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getKfUnendMsg());
    }
    if (((bitField0_ & 0x00000800) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, getKfOnline());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ty.chat.protocol.KfMessage)) {
      return super.equals(obj);
    }
    com.ty.chat.protocol.KfMessage other = (com.ty.chat.protocol.KfMessage) obj;

    if (hasCmd() != other.hasCmd()) return false;
    if (hasCmd()) {
      if (cmd_ != other.cmd_) return false;
    }
    if (hasVersion() != other.hasVersion()) return false;
    if (hasVersion()) {
      if (!getVersion()
          .equals(other.getVersion())) return false;
    }
    if (hasKfReq() != other.hasKfReq()) return false;
    if (hasKfReq()) {
      if (!getKfReq()
          .equals(other.getKfReq())) return false;
    }
    if (hasKfSend() != other.hasKfSend()) return false;
    if (hasKfSend()) {
      if (!getKfSend()
          .equals(other.getKfSend())) return false;
    }
    if (hasKfIsReaded() != other.hasKfIsReaded()) return false;
    if (hasKfIsReaded()) {
      if (!getKfIsReaded()
          .equals(other.getKfIsReaded())) return false;
    }
    if (hasKfAckAndCancel() != other.hasKfAckAndCancel()) return false;
    if (hasKfAckAndCancel()) {
      if (!getKfAckAndCancel()
          .equals(other.getKfAckAndCancel())) return false;
    }
    if (hasKfWithdraw() != other.hasKfWithdraw()) return false;
    if (hasKfWithdraw()) {
      if (!getKfWithdraw()
          .equals(other.getKfWithdraw())) return false;
    }
    if (hasKfHeartbeat() != other.hasKfHeartbeat()) return false;
    if (hasKfHeartbeat()) {
      if (!getKfHeartbeat()
          .equals(other.getKfHeartbeat())) return false;
    }
    if (hasKfSession() != other.hasKfSession()) return false;
    if (hasKfSession()) {
      if (!getKfSession()
          .equals(other.getKfSession())) return false;
    }
    if (hasKfMessageResp() != other.hasKfMessageResp()) return false;
    if (hasKfMessageResp()) {
      if (!getKfMessageResp()
          .equals(other.getKfMessageResp())) return false;
    }
    if (hasKfUnendMsg() != other.hasKfUnendMsg()) return false;
    if (hasKfUnendMsg()) {
      if (!getKfUnendMsg()
          .equals(other.getKfUnendMsg())) return false;
    }
    if (hasKfOnline() != other.hasKfOnline()) return false;
    if (hasKfOnline()) {
      if (!getKfOnline()
          .equals(other.getKfOnline())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCmd()) {
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + cmd_;
    }
    if (hasVersion()) {
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
    }
    if (hasKfReq()) {
      hash = (37 * hash) + KFREQ_FIELD_NUMBER;
      hash = (53 * hash) + getKfReq().hashCode();
    }
    if (hasKfSend()) {
      hash = (37 * hash) + KFSEND_FIELD_NUMBER;
      hash = (53 * hash) + getKfSend().hashCode();
    }
    if (hasKfIsReaded()) {
      hash = (37 * hash) + KFISREADED_FIELD_NUMBER;
      hash = (53 * hash) + getKfIsReaded().hashCode();
    }
    if (hasKfAckAndCancel()) {
      hash = (37 * hash) + KFACKANDCANCEL_FIELD_NUMBER;
      hash = (53 * hash) + getKfAckAndCancel().hashCode();
    }
    if (hasKfWithdraw()) {
      hash = (37 * hash) + KFWITHDRAW_FIELD_NUMBER;
      hash = (53 * hash) + getKfWithdraw().hashCode();
    }
    if (hasKfHeartbeat()) {
      hash = (37 * hash) + KFHEARTBEAT_FIELD_NUMBER;
      hash = (53 * hash) + getKfHeartbeat().hashCode();
    }
    if (hasKfSession()) {
      hash = (37 * hash) + KFSESSION_FIELD_NUMBER;
      hash = (53 * hash) + getKfSession().hashCode();
    }
    if (hasKfMessageResp()) {
      hash = (37 * hash) + KFMESSAGERESP_FIELD_NUMBER;
      hash = (53 * hash) + getKfMessageResp().hashCode();
    }
    if (hasKfUnendMsg()) {
      hash = (37 * hash) + KFUNENDMSG_FIELD_NUMBER;
      hash = (53 * hash) + getKfUnendMsg().hashCode();
    }
    if (hasKfOnline()) {
      hash = (37 * hash) + KFONLINE_FIELD_NUMBER;
      hash = (53 * hash) + getKfOnline().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ty.chat.protocol.KfMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ty.chat.protocol.KfMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ty.chat.protocol.KfMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ty.chat.protocol.KfMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ty.chat.protocol.KfMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ty.chat.protocol.KfMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ty.chat.protocol.KfMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ty.chat.protocol.KfMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ty.chat.protocol.KfMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ty.chat.protocol.KfMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ty.chat.protocol.KfMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ty.chat.protocol.KfMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ty.chat.protocol.KfMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 总的消息 13
   * </pre>
   *
   * Protobuf type {@code protocol.KfMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.KfMessage)
      com.ty.chat.protocol.KfMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ty.chat.protocol.KfMessageOuterClass.internal_static_protocol_KfMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ty.chat.protocol.KfMessageOuterClass.internal_static_protocol_KfMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ty.chat.protocol.KfMessage.class, com.ty.chat.protocol.KfMessage.Builder.class);
    }

    // Construct using com.ty.chat.protocol.KfMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getKfReqFieldBuilder();
        getKfSendFieldBuilder();
        getKfIsReadedFieldBuilder();
        getKfAckAndCancelFieldBuilder();
        getKfWithdrawFieldBuilder();
        getKfHeartbeatFieldBuilder();
        getKfSessionFieldBuilder();
        getKfMessageRespFieldBuilder();
        getKfUnendMsgFieldBuilder();
        getKfOnlineFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      cmd_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = "1.0.0";
      bitField0_ = (bitField0_ & ~0x00000002);
      if (kfReqBuilder_ == null) {
        kfReq_ = null;
      } else {
        kfReqBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (kfSendBuilder_ == null) {
        kfSend_ = null;
      } else {
        kfSendBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      if (kfIsReadedBuilder_ == null) {
        kfIsReaded_ = null;
      } else {
        kfIsReadedBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      if (kfAckAndCancelBuilder_ == null) {
        kfAckAndCancel_ = null;
      } else {
        kfAckAndCancelBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      if (kfWithdrawBuilder_ == null) {
        kfWithdraw_ = null;
      } else {
        kfWithdrawBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      if (kfHeartbeatBuilder_ == null) {
        kfHeartbeat_ = null;
      } else {
        kfHeartbeatBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      if (kfSessionBuilder_ == null) {
        kfSession_ = null;
      } else {
        kfSessionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000100);
      if (kfMessageRespBuilder_ == null) {
        kfMessageResp_ = null;
      } else {
        kfMessageRespBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000200);
      if (kfUnendMsgBuilder_ == null) {
        kfUnendMsg_ = null;
      } else {
        kfUnendMsgBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000400);
      if (kfOnlineBuilder_ == null) {
        kfOnline_ = null;
      } else {
        kfOnlineBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000800);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ty.chat.protocol.KfMessageOuterClass.internal_static_protocol_KfMessage_descriptor;
    }

    @java.lang.Override
    public com.ty.chat.protocol.KfMessage getDefaultInstanceForType() {
      return com.ty.chat.protocol.KfMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.ty.chat.protocol.KfMessage build() {
      com.ty.chat.protocol.KfMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ty.chat.protocol.KfMessage buildPartial() {
      com.ty.chat.protocol.KfMessage result = new com.ty.chat.protocol.KfMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.cmd_ = cmd_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.version_ = version_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        if (kfReqBuilder_ == null) {
          result.kfReq_ = kfReq_;
        } else {
          result.kfReq_ = kfReqBuilder_.build();
        }
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        if (kfSendBuilder_ == null) {
          result.kfSend_ = kfSend_;
        } else {
          result.kfSend_ = kfSendBuilder_.build();
        }
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        if (kfIsReadedBuilder_ == null) {
          result.kfIsReaded_ = kfIsReaded_;
        } else {
          result.kfIsReaded_ = kfIsReadedBuilder_.build();
        }
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        if (kfAckAndCancelBuilder_ == null) {
          result.kfAckAndCancel_ = kfAckAndCancel_;
        } else {
          result.kfAckAndCancel_ = kfAckAndCancelBuilder_.build();
        }
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        if (kfWithdrawBuilder_ == null) {
          result.kfWithdraw_ = kfWithdraw_;
        } else {
          result.kfWithdraw_ = kfWithdrawBuilder_.build();
        }
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        if (kfHeartbeatBuilder_ == null) {
          result.kfHeartbeat_ = kfHeartbeat_;
        } else {
          result.kfHeartbeat_ = kfHeartbeatBuilder_.build();
        }
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        if (kfSessionBuilder_ == null) {
          result.kfSession_ = kfSession_;
        } else {
          result.kfSession_ = kfSessionBuilder_.build();
        }
        to_bitField0_ |= 0x00000100;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        if (kfMessageRespBuilder_ == null) {
          result.kfMessageResp_ = kfMessageResp_;
        } else {
          result.kfMessageResp_ = kfMessageRespBuilder_.build();
        }
        to_bitField0_ |= 0x00000200;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        if (kfUnendMsgBuilder_ == null) {
          result.kfUnendMsg_ = kfUnendMsg_;
        } else {
          result.kfUnendMsg_ = kfUnendMsgBuilder_.build();
        }
        to_bitField0_ |= 0x00000400;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        if (kfOnlineBuilder_ == null) {
          result.kfOnline_ = kfOnline_;
        } else {
          result.kfOnline_ = kfOnlineBuilder_.build();
        }
        to_bitField0_ |= 0x00000800;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ty.chat.protocol.KfMessage) {
        return mergeFrom((com.ty.chat.protocol.KfMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ty.chat.protocol.KfMessage other) {
      if (other == com.ty.chat.protocol.KfMessage.getDefaultInstance()) return this;
      if (other.hasCmd()) {
        setCmd(other.getCmd());
      }
      if (other.hasVersion()) {
        bitField0_ |= 0x00000002;
        version_ = other.version_;
        onChanged();
      }
      if (other.hasKfReq()) {
        mergeKfReq(other.getKfReq());
      }
      if (other.hasKfSend()) {
        mergeKfSend(other.getKfSend());
      }
      if (other.hasKfIsReaded()) {
        mergeKfIsReaded(other.getKfIsReaded());
      }
      if (other.hasKfAckAndCancel()) {
        mergeKfAckAndCancel(other.getKfAckAndCancel());
      }
      if (other.hasKfWithdraw()) {
        mergeKfWithdraw(other.getKfWithdraw());
      }
      if (other.hasKfHeartbeat()) {
        mergeKfHeartbeat(other.getKfHeartbeat());
      }
      if (other.hasKfSession()) {
        mergeKfSession(other.getKfSession());
      }
      if (other.hasKfMessageResp()) {
        mergeKfMessageResp(other.getKfMessageResp());
      }
      if (other.hasKfUnendMsg()) {
        mergeKfUnendMsg(other.getKfUnendMsg());
      }
      if (other.hasKfOnline()) {
        mergeKfOnline(other.getKfOnline());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasCmd()) {
        return false;
      }
      if (hasKfReq()) {
        if (!getKfReq().isInitialized()) {
          return false;
        }
      }
      if (hasKfSend()) {
        if (!getKfSend().isInitialized()) {
          return false;
        }
      }
      if (hasKfIsReaded()) {
        if (!getKfIsReaded().isInitialized()) {
          return false;
        }
      }
      if (hasKfAckAndCancel()) {
        if (!getKfAckAndCancel().isInitialized()) {
          return false;
        }
      }
      if (hasKfWithdraw()) {
        if (!getKfWithdraw().isInitialized()) {
          return false;
        }
      }
      if (hasKfHeartbeat()) {
        if (!getKfHeartbeat().isInitialized()) {
          return false;
        }
      }
      if (hasKfSession()) {
        if (!getKfSession().isInitialized()) {
          return false;
        }
      }
      if (hasKfUnendMsg()) {
        if (!getKfUnendMsg().isInitialized()) {
          return false;
        }
      }
      if (hasKfOnline()) {
        if (!getKfOnline().isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ty.chat.protocol.KfMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ty.chat.protocol.KfMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int cmd_ = 0;
    /**
     * <code>required .protocol.Command cmd = 1;</code>
     * @return Whether the cmd field is set.
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .protocol.Command cmd = 1;</code>
     * @return The cmd.
     */
    public com.ty.chat.protocol.Command getCmd() {
      @SuppressWarnings("deprecation")
      com.ty.chat.protocol.Command result = com.ty.chat.protocol.Command.valueOf(cmd_);
      return result == null ? com.ty.chat.protocol.Command.COMMAND_UNKNOW : result;
    }
    /**
     * <code>required .protocol.Command cmd = 1;</code>
     * @param value The cmd to set.
     * @return This builder for chaining.
     */
    public Builder setCmd(com.ty.chat.protocol.Command value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      cmd_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>required .protocol.Command cmd = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCmd() {
      bitField0_ = (bitField0_ & ~0x00000001);
      cmd_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "1.0.0";
    /**
     * <pre>
     * 版本信息
     * </pre>
     *
     * <code>optional string version = 2 [default = "1.0.0"];</code>
     * @return Whether the version field is set.
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 版本信息
     * </pre>
     *
     * <code>optional string version = 2 [default = "1.0.0"];</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 版本信息
     * </pre>
     *
     * <code>optional string version = 2 [default = "1.0.0"];</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 版本信息
     * </pre>
     *
     * <code>optional string version = 2 [default = "1.0.0"];</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 版本信息
     * </pre>
     *
     * <code>optional string version = 2 [default = "1.0.0"];</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000002);
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 版本信息
     * </pre>
     *
     * <code>optional string version = 2 [default = "1.0.0"];</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      version_ = value;
      onChanged();
      return this;
    }

    private com.ty.chat.protocol.KfReq kfReq_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfReq, com.ty.chat.protocol.KfReq.Builder, com.ty.chat.protocol.KfReqOrBuilder> kfReqBuilder_;
    /**
     * <code>optional .protocol.KfReq kfReq = 3;</code>
     * @return Whether the kfReq field is set.
     */
    public boolean hasKfReq() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .protocol.KfReq kfReq = 3;</code>
     * @return The kfReq.
     */
    public com.ty.chat.protocol.KfReq getKfReq() {
      if (kfReqBuilder_ == null) {
        return kfReq_ == null ? com.ty.chat.protocol.KfReq.getDefaultInstance() : kfReq_;
      } else {
        return kfReqBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .protocol.KfReq kfReq = 3;</code>
     */
    public Builder setKfReq(com.ty.chat.protocol.KfReq value) {
      if (kfReqBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kfReq_ = value;
        onChanged();
      } else {
        kfReqBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .protocol.KfReq kfReq = 3;</code>
     */
    public Builder setKfReq(
        com.ty.chat.protocol.KfReq.Builder builderForValue) {
      if (kfReqBuilder_ == null) {
        kfReq_ = builderForValue.build();
        onChanged();
      } else {
        kfReqBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .protocol.KfReq kfReq = 3;</code>
     */
    public Builder mergeKfReq(com.ty.chat.protocol.KfReq value) {
      if (kfReqBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
            kfReq_ != null &&
            kfReq_ != com.ty.chat.protocol.KfReq.getDefaultInstance()) {
          kfReq_ =
            com.ty.chat.protocol.KfReq.newBuilder(kfReq_).mergeFrom(value).buildPartial();
        } else {
          kfReq_ = value;
        }
        onChanged();
      } else {
        kfReqBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .protocol.KfReq kfReq = 3;</code>
     */
    public Builder clearKfReq() {
      if (kfReqBuilder_ == null) {
        kfReq_ = null;
        onChanged();
      } else {
        kfReqBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>optional .protocol.KfReq kfReq = 3;</code>
     */
    public com.ty.chat.protocol.KfReq.Builder getKfReqBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getKfReqFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .protocol.KfReq kfReq = 3;</code>
     */
    public com.ty.chat.protocol.KfReqOrBuilder getKfReqOrBuilder() {
      if (kfReqBuilder_ != null) {
        return kfReqBuilder_.getMessageOrBuilder();
      } else {
        return kfReq_ == null ?
            com.ty.chat.protocol.KfReq.getDefaultInstance() : kfReq_;
      }
    }
    /**
     * <code>optional .protocol.KfReq kfReq = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfReq, com.ty.chat.protocol.KfReq.Builder, com.ty.chat.protocol.KfReqOrBuilder> 
        getKfReqFieldBuilder() {
      if (kfReqBuilder_ == null) {
        kfReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ty.chat.protocol.KfReq, com.ty.chat.protocol.KfReq.Builder, com.ty.chat.protocol.KfReqOrBuilder>(
                getKfReq(),
                getParentForChildren(),
                isClean());
        kfReq_ = null;
      }
      return kfReqBuilder_;
    }

    private com.ty.chat.protocol.KfSend kfSend_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfSend, com.ty.chat.protocol.KfSend.Builder, com.ty.chat.protocol.KfSendOrBuilder> kfSendBuilder_;
    /**
     * <code>optional .protocol.KfSend kfSend = 4;</code>
     * @return Whether the kfSend field is set.
     */
    public boolean hasKfSend() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .protocol.KfSend kfSend = 4;</code>
     * @return The kfSend.
     */
    public com.ty.chat.protocol.KfSend getKfSend() {
      if (kfSendBuilder_ == null) {
        return kfSend_ == null ? com.ty.chat.protocol.KfSend.getDefaultInstance() : kfSend_;
      } else {
        return kfSendBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .protocol.KfSend kfSend = 4;</code>
     */
    public Builder setKfSend(com.ty.chat.protocol.KfSend value) {
      if (kfSendBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kfSend_ = value;
        onChanged();
      } else {
        kfSendBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .protocol.KfSend kfSend = 4;</code>
     */
    public Builder setKfSend(
        com.ty.chat.protocol.KfSend.Builder builderForValue) {
      if (kfSendBuilder_ == null) {
        kfSend_ = builderForValue.build();
        onChanged();
      } else {
        kfSendBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .protocol.KfSend kfSend = 4;</code>
     */
    public Builder mergeKfSend(com.ty.chat.protocol.KfSend value) {
      if (kfSendBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
            kfSend_ != null &&
            kfSend_ != com.ty.chat.protocol.KfSend.getDefaultInstance()) {
          kfSend_ =
            com.ty.chat.protocol.KfSend.newBuilder(kfSend_).mergeFrom(value).buildPartial();
        } else {
          kfSend_ = value;
        }
        onChanged();
      } else {
        kfSendBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .protocol.KfSend kfSend = 4;</code>
     */
    public Builder clearKfSend() {
      if (kfSendBuilder_ == null) {
        kfSend_ = null;
        onChanged();
      } else {
        kfSendBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }
    /**
     * <code>optional .protocol.KfSend kfSend = 4;</code>
     */
    public com.ty.chat.protocol.KfSend.Builder getKfSendBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getKfSendFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .protocol.KfSend kfSend = 4;</code>
     */
    public com.ty.chat.protocol.KfSendOrBuilder getKfSendOrBuilder() {
      if (kfSendBuilder_ != null) {
        return kfSendBuilder_.getMessageOrBuilder();
      } else {
        return kfSend_ == null ?
            com.ty.chat.protocol.KfSend.getDefaultInstance() : kfSend_;
      }
    }
    /**
     * <code>optional .protocol.KfSend kfSend = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfSend, com.ty.chat.protocol.KfSend.Builder, com.ty.chat.protocol.KfSendOrBuilder> 
        getKfSendFieldBuilder() {
      if (kfSendBuilder_ == null) {
        kfSendBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ty.chat.protocol.KfSend, com.ty.chat.protocol.KfSend.Builder, com.ty.chat.protocol.KfSendOrBuilder>(
                getKfSend(),
                getParentForChildren(),
                isClean());
        kfSend_ = null;
      }
      return kfSendBuilder_;
    }

    private com.ty.chat.protocol.KfIsReaded kfIsReaded_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfIsReaded, com.ty.chat.protocol.KfIsReaded.Builder, com.ty.chat.protocol.KfIsReadedOrBuilder> kfIsReadedBuilder_;
    /**
     * <code>optional .protocol.KfIsReaded kfIsReaded = 5;</code>
     * @return Whether the kfIsReaded field is set.
     */
    public boolean hasKfIsReaded() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .protocol.KfIsReaded kfIsReaded = 5;</code>
     * @return The kfIsReaded.
     */
    public com.ty.chat.protocol.KfIsReaded getKfIsReaded() {
      if (kfIsReadedBuilder_ == null) {
        return kfIsReaded_ == null ? com.ty.chat.protocol.KfIsReaded.getDefaultInstance() : kfIsReaded_;
      } else {
        return kfIsReadedBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .protocol.KfIsReaded kfIsReaded = 5;</code>
     */
    public Builder setKfIsReaded(com.ty.chat.protocol.KfIsReaded value) {
      if (kfIsReadedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kfIsReaded_ = value;
        onChanged();
      } else {
        kfIsReadedBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .protocol.KfIsReaded kfIsReaded = 5;</code>
     */
    public Builder setKfIsReaded(
        com.ty.chat.protocol.KfIsReaded.Builder builderForValue) {
      if (kfIsReadedBuilder_ == null) {
        kfIsReaded_ = builderForValue.build();
        onChanged();
      } else {
        kfIsReadedBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .protocol.KfIsReaded kfIsReaded = 5;</code>
     */
    public Builder mergeKfIsReaded(com.ty.chat.protocol.KfIsReaded value) {
      if (kfIsReadedBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
            kfIsReaded_ != null &&
            kfIsReaded_ != com.ty.chat.protocol.KfIsReaded.getDefaultInstance()) {
          kfIsReaded_ =
            com.ty.chat.protocol.KfIsReaded.newBuilder(kfIsReaded_).mergeFrom(value).buildPartial();
        } else {
          kfIsReaded_ = value;
        }
        onChanged();
      } else {
        kfIsReadedBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .protocol.KfIsReaded kfIsReaded = 5;</code>
     */
    public Builder clearKfIsReaded() {
      if (kfIsReadedBuilder_ == null) {
        kfIsReaded_ = null;
        onChanged();
      } else {
        kfIsReadedBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }
    /**
     * <code>optional .protocol.KfIsReaded kfIsReaded = 5;</code>
     */
    public com.ty.chat.protocol.KfIsReaded.Builder getKfIsReadedBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getKfIsReadedFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .protocol.KfIsReaded kfIsReaded = 5;</code>
     */
    public com.ty.chat.protocol.KfIsReadedOrBuilder getKfIsReadedOrBuilder() {
      if (kfIsReadedBuilder_ != null) {
        return kfIsReadedBuilder_.getMessageOrBuilder();
      } else {
        return kfIsReaded_ == null ?
            com.ty.chat.protocol.KfIsReaded.getDefaultInstance() : kfIsReaded_;
      }
    }
    /**
     * <code>optional .protocol.KfIsReaded kfIsReaded = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfIsReaded, com.ty.chat.protocol.KfIsReaded.Builder, com.ty.chat.protocol.KfIsReadedOrBuilder> 
        getKfIsReadedFieldBuilder() {
      if (kfIsReadedBuilder_ == null) {
        kfIsReadedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ty.chat.protocol.KfIsReaded, com.ty.chat.protocol.KfIsReaded.Builder, com.ty.chat.protocol.KfIsReadedOrBuilder>(
                getKfIsReaded(),
                getParentForChildren(),
                isClean());
        kfIsReaded_ = null;
      }
      return kfIsReadedBuilder_;
    }

    private com.ty.chat.protocol.KfAckAndCancel kfAckAndCancel_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfAckAndCancel, com.ty.chat.protocol.KfAckAndCancel.Builder, com.ty.chat.protocol.KfAckAndCancelOrBuilder> kfAckAndCancelBuilder_;
    /**
     * <code>optional .protocol.KfAckAndCancel kfAckAndCancel = 6;</code>
     * @return Whether the kfAckAndCancel field is set.
     */
    public boolean hasKfAckAndCancel() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional .protocol.KfAckAndCancel kfAckAndCancel = 6;</code>
     * @return The kfAckAndCancel.
     */
    public com.ty.chat.protocol.KfAckAndCancel getKfAckAndCancel() {
      if (kfAckAndCancelBuilder_ == null) {
        return kfAckAndCancel_ == null ? com.ty.chat.protocol.KfAckAndCancel.getDefaultInstance() : kfAckAndCancel_;
      } else {
        return kfAckAndCancelBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .protocol.KfAckAndCancel kfAckAndCancel = 6;</code>
     */
    public Builder setKfAckAndCancel(com.ty.chat.protocol.KfAckAndCancel value) {
      if (kfAckAndCancelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kfAckAndCancel_ = value;
        onChanged();
      } else {
        kfAckAndCancelBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>optional .protocol.KfAckAndCancel kfAckAndCancel = 6;</code>
     */
    public Builder setKfAckAndCancel(
        com.ty.chat.protocol.KfAckAndCancel.Builder builderForValue) {
      if (kfAckAndCancelBuilder_ == null) {
        kfAckAndCancel_ = builderForValue.build();
        onChanged();
      } else {
        kfAckAndCancelBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>optional .protocol.KfAckAndCancel kfAckAndCancel = 6;</code>
     */
    public Builder mergeKfAckAndCancel(com.ty.chat.protocol.KfAckAndCancel value) {
      if (kfAckAndCancelBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
            kfAckAndCancel_ != null &&
            kfAckAndCancel_ != com.ty.chat.protocol.KfAckAndCancel.getDefaultInstance()) {
          kfAckAndCancel_ =
            com.ty.chat.protocol.KfAckAndCancel.newBuilder(kfAckAndCancel_).mergeFrom(value).buildPartial();
        } else {
          kfAckAndCancel_ = value;
        }
        onChanged();
      } else {
        kfAckAndCancelBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>optional .protocol.KfAckAndCancel kfAckAndCancel = 6;</code>
     */
    public Builder clearKfAckAndCancel() {
      if (kfAckAndCancelBuilder_ == null) {
        kfAckAndCancel_ = null;
        onChanged();
      } else {
        kfAckAndCancelBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }
    /**
     * <code>optional .protocol.KfAckAndCancel kfAckAndCancel = 6;</code>
     */
    public com.ty.chat.protocol.KfAckAndCancel.Builder getKfAckAndCancelBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getKfAckAndCancelFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .protocol.KfAckAndCancel kfAckAndCancel = 6;</code>
     */
    public com.ty.chat.protocol.KfAckAndCancelOrBuilder getKfAckAndCancelOrBuilder() {
      if (kfAckAndCancelBuilder_ != null) {
        return kfAckAndCancelBuilder_.getMessageOrBuilder();
      } else {
        return kfAckAndCancel_ == null ?
            com.ty.chat.protocol.KfAckAndCancel.getDefaultInstance() : kfAckAndCancel_;
      }
    }
    /**
     * <code>optional .protocol.KfAckAndCancel kfAckAndCancel = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfAckAndCancel, com.ty.chat.protocol.KfAckAndCancel.Builder, com.ty.chat.protocol.KfAckAndCancelOrBuilder> 
        getKfAckAndCancelFieldBuilder() {
      if (kfAckAndCancelBuilder_ == null) {
        kfAckAndCancelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ty.chat.protocol.KfAckAndCancel, com.ty.chat.protocol.KfAckAndCancel.Builder, com.ty.chat.protocol.KfAckAndCancelOrBuilder>(
                getKfAckAndCancel(),
                getParentForChildren(),
                isClean());
        kfAckAndCancel_ = null;
      }
      return kfAckAndCancelBuilder_;
    }

    private com.ty.chat.protocol.KfWithdraw kfWithdraw_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfWithdraw, com.ty.chat.protocol.KfWithdraw.Builder, com.ty.chat.protocol.KfWithdrawOrBuilder> kfWithdrawBuilder_;
    /**
     * <code>optional .protocol.KfWithdraw kfWithdraw = 7;</code>
     * @return Whether the kfWithdraw field is set.
     */
    public boolean hasKfWithdraw() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional .protocol.KfWithdraw kfWithdraw = 7;</code>
     * @return The kfWithdraw.
     */
    public com.ty.chat.protocol.KfWithdraw getKfWithdraw() {
      if (kfWithdrawBuilder_ == null) {
        return kfWithdraw_ == null ? com.ty.chat.protocol.KfWithdraw.getDefaultInstance() : kfWithdraw_;
      } else {
        return kfWithdrawBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .protocol.KfWithdraw kfWithdraw = 7;</code>
     */
    public Builder setKfWithdraw(com.ty.chat.protocol.KfWithdraw value) {
      if (kfWithdrawBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kfWithdraw_ = value;
        onChanged();
      } else {
        kfWithdrawBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>optional .protocol.KfWithdraw kfWithdraw = 7;</code>
     */
    public Builder setKfWithdraw(
        com.ty.chat.protocol.KfWithdraw.Builder builderForValue) {
      if (kfWithdrawBuilder_ == null) {
        kfWithdraw_ = builderForValue.build();
        onChanged();
      } else {
        kfWithdrawBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>optional .protocol.KfWithdraw kfWithdraw = 7;</code>
     */
    public Builder mergeKfWithdraw(com.ty.chat.protocol.KfWithdraw value) {
      if (kfWithdrawBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
            kfWithdraw_ != null &&
            kfWithdraw_ != com.ty.chat.protocol.KfWithdraw.getDefaultInstance()) {
          kfWithdraw_ =
            com.ty.chat.protocol.KfWithdraw.newBuilder(kfWithdraw_).mergeFrom(value).buildPartial();
        } else {
          kfWithdraw_ = value;
        }
        onChanged();
      } else {
        kfWithdrawBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>optional .protocol.KfWithdraw kfWithdraw = 7;</code>
     */
    public Builder clearKfWithdraw() {
      if (kfWithdrawBuilder_ == null) {
        kfWithdraw_ = null;
        onChanged();
      } else {
        kfWithdrawBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }
    /**
     * <code>optional .protocol.KfWithdraw kfWithdraw = 7;</code>
     */
    public com.ty.chat.protocol.KfWithdraw.Builder getKfWithdrawBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getKfWithdrawFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .protocol.KfWithdraw kfWithdraw = 7;</code>
     */
    public com.ty.chat.protocol.KfWithdrawOrBuilder getKfWithdrawOrBuilder() {
      if (kfWithdrawBuilder_ != null) {
        return kfWithdrawBuilder_.getMessageOrBuilder();
      } else {
        return kfWithdraw_ == null ?
            com.ty.chat.protocol.KfWithdraw.getDefaultInstance() : kfWithdraw_;
      }
    }
    /**
     * <code>optional .protocol.KfWithdraw kfWithdraw = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfWithdraw, com.ty.chat.protocol.KfWithdraw.Builder, com.ty.chat.protocol.KfWithdrawOrBuilder> 
        getKfWithdrawFieldBuilder() {
      if (kfWithdrawBuilder_ == null) {
        kfWithdrawBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ty.chat.protocol.KfWithdraw, com.ty.chat.protocol.KfWithdraw.Builder, com.ty.chat.protocol.KfWithdrawOrBuilder>(
                getKfWithdraw(),
                getParentForChildren(),
                isClean());
        kfWithdraw_ = null;
      }
      return kfWithdrawBuilder_;
    }

    private com.ty.chat.protocol.KfHeartbeat kfHeartbeat_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfHeartbeat, com.ty.chat.protocol.KfHeartbeat.Builder, com.ty.chat.protocol.KfHeartbeatOrBuilder> kfHeartbeatBuilder_;
    /**
     * <code>optional .protocol.KfHeartbeat kfHeartbeat = 8;</code>
     * @return Whether the kfHeartbeat field is set.
     */
    public boolean hasKfHeartbeat() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional .protocol.KfHeartbeat kfHeartbeat = 8;</code>
     * @return The kfHeartbeat.
     */
    public com.ty.chat.protocol.KfHeartbeat getKfHeartbeat() {
      if (kfHeartbeatBuilder_ == null) {
        return kfHeartbeat_ == null ? com.ty.chat.protocol.KfHeartbeat.getDefaultInstance() : kfHeartbeat_;
      } else {
        return kfHeartbeatBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .protocol.KfHeartbeat kfHeartbeat = 8;</code>
     */
    public Builder setKfHeartbeat(com.ty.chat.protocol.KfHeartbeat value) {
      if (kfHeartbeatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kfHeartbeat_ = value;
        onChanged();
      } else {
        kfHeartbeatBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      return this;
    }
    /**
     * <code>optional .protocol.KfHeartbeat kfHeartbeat = 8;</code>
     */
    public Builder setKfHeartbeat(
        com.ty.chat.protocol.KfHeartbeat.Builder builderForValue) {
      if (kfHeartbeatBuilder_ == null) {
        kfHeartbeat_ = builderForValue.build();
        onChanged();
      } else {
        kfHeartbeatBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      return this;
    }
    /**
     * <code>optional .protocol.KfHeartbeat kfHeartbeat = 8;</code>
     */
    public Builder mergeKfHeartbeat(com.ty.chat.protocol.KfHeartbeat value) {
      if (kfHeartbeatBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
            kfHeartbeat_ != null &&
            kfHeartbeat_ != com.ty.chat.protocol.KfHeartbeat.getDefaultInstance()) {
          kfHeartbeat_ =
            com.ty.chat.protocol.KfHeartbeat.newBuilder(kfHeartbeat_).mergeFrom(value).buildPartial();
        } else {
          kfHeartbeat_ = value;
        }
        onChanged();
      } else {
        kfHeartbeatBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000080;
      return this;
    }
    /**
     * <code>optional .protocol.KfHeartbeat kfHeartbeat = 8;</code>
     */
    public Builder clearKfHeartbeat() {
      if (kfHeartbeatBuilder_ == null) {
        kfHeartbeat_ = null;
        onChanged();
      } else {
        kfHeartbeatBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }
    /**
     * <code>optional .protocol.KfHeartbeat kfHeartbeat = 8;</code>
     */
    public com.ty.chat.protocol.KfHeartbeat.Builder getKfHeartbeatBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getKfHeartbeatFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .protocol.KfHeartbeat kfHeartbeat = 8;</code>
     */
    public com.ty.chat.protocol.KfHeartbeatOrBuilder getKfHeartbeatOrBuilder() {
      if (kfHeartbeatBuilder_ != null) {
        return kfHeartbeatBuilder_.getMessageOrBuilder();
      } else {
        return kfHeartbeat_ == null ?
            com.ty.chat.protocol.KfHeartbeat.getDefaultInstance() : kfHeartbeat_;
      }
    }
    /**
     * <code>optional .protocol.KfHeartbeat kfHeartbeat = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfHeartbeat, com.ty.chat.protocol.KfHeartbeat.Builder, com.ty.chat.protocol.KfHeartbeatOrBuilder> 
        getKfHeartbeatFieldBuilder() {
      if (kfHeartbeatBuilder_ == null) {
        kfHeartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ty.chat.protocol.KfHeartbeat, com.ty.chat.protocol.KfHeartbeat.Builder, com.ty.chat.protocol.KfHeartbeatOrBuilder>(
                getKfHeartbeat(),
                getParentForChildren(),
                isClean());
        kfHeartbeat_ = null;
      }
      return kfHeartbeatBuilder_;
    }

    private com.ty.chat.protocol.KfSession kfSession_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfSession, com.ty.chat.protocol.KfSession.Builder, com.ty.chat.protocol.KfSessionOrBuilder> kfSessionBuilder_;
    /**
     * <code>optional .protocol.KfSession kfSession = 9;</code>
     * @return Whether the kfSession field is set.
     */
    public boolean hasKfSession() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional .protocol.KfSession kfSession = 9;</code>
     * @return The kfSession.
     */
    public com.ty.chat.protocol.KfSession getKfSession() {
      if (kfSessionBuilder_ == null) {
        return kfSession_ == null ? com.ty.chat.protocol.KfSession.getDefaultInstance() : kfSession_;
      } else {
        return kfSessionBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .protocol.KfSession kfSession = 9;</code>
     */
    public Builder setKfSession(com.ty.chat.protocol.KfSession value) {
      if (kfSessionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kfSession_ = value;
        onChanged();
      } else {
        kfSessionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      return this;
    }
    /**
     * <code>optional .protocol.KfSession kfSession = 9;</code>
     */
    public Builder setKfSession(
        com.ty.chat.protocol.KfSession.Builder builderForValue) {
      if (kfSessionBuilder_ == null) {
        kfSession_ = builderForValue.build();
        onChanged();
      } else {
        kfSessionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      return this;
    }
    /**
     * <code>optional .protocol.KfSession kfSession = 9;</code>
     */
    public Builder mergeKfSession(com.ty.chat.protocol.KfSession value) {
      if (kfSessionBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
            kfSession_ != null &&
            kfSession_ != com.ty.chat.protocol.KfSession.getDefaultInstance()) {
          kfSession_ =
            com.ty.chat.protocol.KfSession.newBuilder(kfSession_).mergeFrom(value).buildPartial();
        } else {
          kfSession_ = value;
        }
        onChanged();
      } else {
        kfSessionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000100;
      return this;
    }
    /**
     * <code>optional .protocol.KfSession kfSession = 9;</code>
     */
    public Builder clearKfSession() {
      if (kfSessionBuilder_ == null) {
        kfSession_ = null;
        onChanged();
      } else {
        kfSessionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }
    /**
     * <code>optional .protocol.KfSession kfSession = 9;</code>
     */
    public com.ty.chat.protocol.KfSession.Builder getKfSessionBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return getKfSessionFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .protocol.KfSession kfSession = 9;</code>
     */
    public com.ty.chat.protocol.KfSessionOrBuilder getKfSessionOrBuilder() {
      if (kfSessionBuilder_ != null) {
        return kfSessionBuilder_.getMessageOrBuilder();
      } else {
        return kfSession_ == null ?
            com.ty.chat.protocol.KfSession.getDefaultInstance() : kfSession_;
      }
    }
    /**
     * <code>optional .protocol.KfSession kfSession = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfSession, com.ty.chat.protocol.KfSession.Builder, com.ty.chat.protocol.KfSessionOrBuilder> 
        getKfSessionFieldBuilder() {
      if (kfSessionBuilder_ == null) {
        kfSessionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ty.chat.protocol.KfSession, com.ty.chat.protocol.KfSession.Builder, com.ty.chat.protocol.KfSessionOrBuilder>(
                getKfSession(),
                getParentForChildren(),
                isClean());
        kfSession_ = null;
      }
      return kfSessionBuilder_;
    }

    private com.ty.chat.protocol.KfMessageResp kfMessageResp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfMessageResp, com.ty.chat.protocol.KfMessageResp.Builder, com.ty.chat.protocol.KfMessageRespOrBuilder> kfMessageRespBuilder_;
    /**
     * <code>optional .protocol.KfMessageResp kfMessageResp = 10;</code>
     * @return Whether the kfMessageResp field is set.
     */
    public boolean hasKfMessageResp() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional .protocol.KfMessageResp kfMessageResp = 10;</code>
     * @return The kfMessageResp.
     */
    public com.ty.chat.protocol.KfMessageResp getKfMessageResp() {
      if (kfMessageRespBuilder_ == null) {
        return kfMessageResp_ == null ? com.ty.chat.protocol.KfMessageResp.getDefaultInstance() : kfMessageResp_;
      } else {
        return kfMessageRespBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .protocol.KfMessageResp kfMessageResp = 10;</code>
     */
    public Builder setKfMessageResp(com.ty.chat.protocol.KfMessageResp value) {
      if (kfMessageRespBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kfMessageResp_ = value;
        onChanged();
      } else {
        kfMessageRespBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000200;
      return this;
    }
    /**
     * <code>optional .protocol.KfMessageResp kfMessageResp = 10;</code>
     */
    public Builder setKfMessageResp(
        com.ty.chat.protocol.KfMessageResp.Builder builderForValue) {
      if (kfMessageRespBuilder_ == null) {
        kfMessageResp_ = builderForValue.build();
        onChanged();
      } else {
        kfMessageRespBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000200;
      return this;
    }
    /**
     * <code>optional .protocol.KfMessageResp kfMessageResp = 10;</code>
     */
    public Builder mergeKfMessageResp(com.ty.chat.protocol.KfMessageResp value) {
      if (kfMessageRespBuilder_ == null) {
        if (((bitField0_ & 0x00000200) != 0) &&
            kfMessageResp_ != null &&
            kfMessageResp_ != com.ty.chat.protocol.KfMessageResp.getDefaultInstance()) {
          kfMessageResp_ =
            com.ty.chat.protocol.KfMessageResp.newBuilder(kfMessageResp_).mergeFrom(value).buildPartial();
        } else {
          kfMessageResp_ = value;
        }
        onChanged();
      } else {
        kfMessageRespBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000200;
      return this;
    }
    /**
     * <code>optional .protocol.KfMessageResp kfMessageResp = 10;</code>
     */
    public Builder clearKfMessageResp() {
      if (kfMessageRespBuilder_ == null) {
        kfMessageResp_ = null;
        onChanged();
      } else {
        kfMessageRespBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000200);
      return this;
    }
    /**
     * <code>optional .protocol.KfMessageResp kfMessageResp = 10;</code>
     */
    public com.ty.chat.protocol.KfMessageResp.Builder getKfMessageRespBuilder() {
      bitField0_ |= 0x00000200;
      onChanged();
      return getKfMessageRespFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .protocol.KfMessageResp kfMessageResp = 10;</code>
     */
    public com.ty.chat.protocol.KfMessageRespOrBuilder getKfMessageRespOrBuilder() {
      if (kfMessageRespBuilder_ != null) {
        return kfMessageRespBuilder_.getMessageOrBuilder();
      } else {
        return kfMessageResp_ == null ?
            com.ty.chat.protocol.KfMessageResp.getDefaultInstance() : kfMessageResp_;
      }
    }
    /**
     * <code>optional .protocol.KfMessageResp kfMessageResp = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfMessageResp, com.ty.chat.protocol.KfMessageResp.Builder, com.ty.chat.protocol.KfMessageRespOrBuilder> 
        getKfMessageRespFieldBuilder() {
      if (kfMessageRespBuilder_ == null) {
        kfMessageRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ty.chat.protocol.KfMessageResp, com.ty.chat.protocol.KfMessageResp.Builder, com.ty.chat.protocol.KfMessageRespOrBuilder>(
                getKfMessageResp(),
                getParentForChildren(),
                isClean());
        kfMessageResp_ = null;
      }
      return kfMessageRespBuilder_;
    }

    private com.ty.chat.protocol.KfUnendMsg kfUnendMsg_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfUnendMsg, com.ty.chat.protocol.KfUnendMsg.Builder, com.ty.chat.protocol.KfUnendMsgOrBuilder> kfUnendMsgBuilder_;
    /**
     * <code>optional .protocol.KfUnendMsg kfUnendMsg = 11;</code>
     * @return Whether the kfUnendMsg field is set.
     */
    public boolean hasKfUnendMsg() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional .protocol.KfUnendMsg kfUnendMsg = 11;</code>
     * @return The kfUnendMsg.
     */
    public com.ty.chat.protocol.KfUnendMsg getKfUnendMsg() {
      if (kfUnendMsgBuilder_ == null) {
        return kfUnendMsg_ == null ? com.ty.chat.protocol.KfUnendMsg.getDefaultInstance() : kfUnendMsg_;
      } else {
        return kfUnendMsgBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .protocol.KfUnendMsg kfUnendMsg = 11;</code>
     */
    public Builder setKfUnendMsg(com.ty.chat.protocol.KfUnendMsg value) {
      if (kfUnendMsgBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kfUnendMsg_ = value;
        onChanged();
      } else {
        kfUnendMsgBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000400;
      return this;
    }
    /**
     * <code>optional .protocol.KfUnendMsg kfUnendMsg = 11;</code>
     */
    public Builder setKfUnendMsg(
        com.ty.chat.protocol.KfUnendMsg.Builder builderForValue) {
      if (kfUnendMsgBuilder_ == null) {
        kfUnendMsg_ = builderForValue.build();
        onChanged();
      } else {
        kfUnendMsgBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000400;
      return this;
    }
    /**
     * <code>optional .protocol.KfUnendMsg kfUnendMsg = 11;</code>
     */
    public Builder mergeKfUnendMsg(com.ty.chat.protocol.KfUnendMsg value) {
      if (kfUnendMsgBuilder_ == null) {
        if (((bitField0_ & 0x00000400) != 0) &&
            kfUnendMsg_ != null &&
            kfUnendMsg_ != com.ty.chat.protocol.KfUnendMsg.getDefaultInstance()) {
          kfUnendMsg_ =
            com.ty.chat.protocol.KfUnendMsg.newBuilder(kfUnendMsg_).mergeFrom(value).buildPartial();
        } else {
          kfUnendMsg_ = value;
        }
        onChanged();
      } else {
        kfUnendMsgBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000400;
      return this;
    }
    /**
     * <code>optional .protocol.KfUnendMsg kfUnendMsg = 11;</code>
     */
    public Builder clearKfUnendMsg() {
      if (kfUnendMsgBuilder_ == null) {
        kfUnendMsg_ = null;
        onChanged();
      } else {
        kfUnendMsgBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000400);
      return this;
    }
    /**
     * <code>optional .protocol.KfUnendMsg kfUnendMsg = 11;</code>
     */
    public com.ty.chat.protocol.KfUnendMsg.Builder getKfUnendMsgBuilder() {
      bitField0_ |= 0x00000400;
      onChanged();
      return getKfUnendMsgFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .protocol.KfUnendMsg kfUnendMsg = 11;</code>
     */
    public com.ty.chat.protocol.KfUnendMsgOrBuilder getKfUnendMsgOrBuilder() {
      if (kfUnendMsgBuilder_ != null) {
        return kfUnendMsgBuilder_.getMessageOrBuilder();
      } else {
        return kfUnendMsg_ == null ?
            com.ty.chat.protocol.KfUnendMsg.getDefaultInstance() : kfUnendMsg_;
      }
    }
    /**
     * <code>optional .protocol.KfUnendMsg kfUnendMsg = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfUnendMsg, com.ty.chat.protocol.KfUnendMsg.Builder, com.ty.chat.protocol.KfUnendMsgOrBuilder> 
        getKfUnendMsgFieldBuilder() {
      if (kfUnendMsgBuilder_ == null) {
        kfUnendMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ty.chat.protocol.KfUnendMsg, com.ty.chat.protocol.KfUnendMsg.Builder, com.ty.chat.protocol.KfUnendMsgOrBuilder>(
                getKfUnendMsg(),
                getParentForChildren(),
                isClean());
        kfUnendMsg_ = null;
      }
      return kfUnendMsgBuilder_;
    }

    private com.ty.chat.protocol.KfOnline kfOnline_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfOnline, com.ty.chat.protocol.KfOnline.Builder, com.ty.chat.protocol.KfOnlineOrBuilder> kfOnlineBuilder_;
    /**
     * <code>optional .protocol.KfOnline kfOnline = 12;</code>
     * @return Whether the kfOnline field is set.
     */
    public boolean hasKfOnline() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>optional .protocol.KfOnline kfOnline = 12;</code>
     * @return The kfOnline.
     */
    public com.ty.chat.protocol.KfOnline getKfOnline() {
      if (kfOnlineBuilder_ == null) {
        return kfOnline_ == null ? com.ty.chat.protocol.KfOnline.getDefaultInstance() : kfOnline_;
      } else {
        return kfOnlineBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .protocol.KfOnline kfOnline = 12;</code>
     */
    public Builder setKfOnline(com.ty.chat.protocol.KfOnline value) {
      if (kfOnlineBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kfOnline_ = value;
        onChanged();
      } else {
        kfOnlineBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000800;
      return this;
    }
    /**
     * <code>optional .protocol.KfOnline kfOnline = 12;</code>
     */
    public Builder setKfOnline(
        com.ty.chat.protocol.KfOnline.Builder builderForValue) {
      if (kfOnlineBuilder_ == null) {
        kfOnline_ = builderForValue.build();
        onChanged();
      } else {
        kfOnlineBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000800;
      return this;
    }
    /**
     * <code>optional .protocol.KfOnline kfOnline = 12;</code>
     */
    public Builder mergeKfOnline(com.ty.chat.protocol.KfOnline value) {
      if (kfOnlineBuilder_ == null) {
        if (((bitField0_ & 0x00000800) != 0) &&
            kfOnline_ != null &&
            kfOnline_ != com.ty.chat.protocol.KfOnline.getDefaultInstance()) {
          kfOnline_ =
            com.ty.chat.protocol.KfOnline.newBuilder(kfOnline_).mergeFrom(value).buildPartial();
        } else {
          kfOnline_ = value;
        }
        onChanged();
      } else {
        kfOnlineBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000800;
      return this;
    }
    /**
     * <code>optional .protocol.KfOnline kfOnline = 12;</code>
     */
    public Builder clearKfOnline() {
      if (kfOnlineBuilder_ == null) {
        kfOnline_ = null;
        onChanged();
      } else {
        kfOnlineBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000800);
      return this;
    }
    /**
     * <code>optional .protocol.KfOnline kfOnline = 12;</code>
     */
    public com.ty.chat.protocol.KfOnline.Builder getKfOnlineBuilder() {
      bitField0_ |= 0x00000800;
      onChanged();
      return getKfOnlineFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .protocol.KfOnline kfOnline = 12;</code>
     */
    public com.ty.chat.protocol.KfOnlineOrBuilder getKfOnlineOrBuilder() {
      if (kfOnlineBuilder_ != null) {
        return kfOnlineBuilder_.getMessageOrBuilder();
      } else {
        return kfOnline_ == null ?
            com.ty.chat.protocol.KfOnline.getDefaultInstance() : kfOnline_;
      }
    }
    /**
     * <code>optional .protocol.KfOnline kfOnline = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ty.chat.protocol.KfOnline, com.ty.chat.protocol.KfOnline.Builder, com.ty.chat.protocol.KfOnlineOrBuilder> 
        getKfOnlineFieldBuilder() {
      if (kfOnlineBuilder_ == null) {
        kfOnlineBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ty.chat.protocol.KfOnline, com.ty.chat.protocol.KfOnline.Builder, com.ty.chat.protocol.KfOnlineOrBuilder>(
                getKfOnline(),
                getParentForChildren(),
                isClean());
        kfOnline_ = null;
      }
      return kfOnlineBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.KfMessage)
  }

  // @@protoc_insertion_point(class_scope:protocol.KfMessage)
  private static final com.ty.chat.protocol.KfMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ty.chat.protocol.KfMessage();
  }

  public static com.ty.chat.protocol.KfMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<KfMessage>
      PARSER = new com.google.protobuf.AbstractParser<KfMessage>() {
    @java.lang.Override
    public KfMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new KfMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<KfMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KfMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ty.chat.protocol.KfMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

