// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kfMessage.proto

package com.ty.chat.protocol;

public interface KfOnlineOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.KfOnline)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string fromId = 1;</code>
   * @return Whether the fromId field is set.
   */
  boolean hasFromId();
  /**
   * <code>required string fromId = 1;</code>
   * @return The fromId.
   */
  java.lang.String getFromId();
  /**
   * <code>required string fromId = 1;</code>
   * @return The bytes for fromId.
   */
  com.google.protobuf.ByteString
      getFromIdBytes();

  /**
   * <code>required string appkey = 2;</code>
   * @return Whether the appkey field is set.
   */
  boolean hasAppkey();
  /**
   * <code>required string appkey = 2;</code>
   * @return The appkey.
   */
  java.lang.String getAppkey();
  /**
   * <code>required string appkey = 2;</code>
   * @return The bytes for appkey.
   */
  com.google.protobuf.ByteString
      getAppkeyBytes();

  /**
   * <code>required string appRequestSource = 3;</code>
   * @return Whether the appRequestSource field is set.
   */
  boolean hasAppRequestSource();
  /**
   * <code>required string appRequestSource = 3;</code>
   * @return The appRequestSource.
   */
  java.lang.String getAppRequestSource();
  /**
   * <code>required string appRequestSource = 3;</code>
   * @return The bytes for appRequestSource.
   */
  com.google.protobuf.ByteString
      getAppRequestSourceBytes();

  /**
   * <code>optional string appSig = 4;</code>
   * @return Whether the appSig field is set.
   */
  boolean hasAppSig();
  /**
   * <code>optional string appSig = 4;</code>
   * @return The appSig.
   */
  java.lang.String getAppSig();
  /**
   * <code>optional string appSig = 4;</code>
   * @return The bytes for appSig.
   */
  com.google.protobuf.ByteString
      getAppSigBytes();

  /**
   * <code>optional string status = 5;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>optional string status = 5;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>optional string status = 5;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
