// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kfMessage.proto

package com.ty.chat.protocol;

public interface KfWithdrawOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.KfWithdraw)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 传输人 、协同人，多个逗号隔开
   * </pre>
   *
   * <code>optional string toId = 1;</code>
   * @return Whether the toId field is set.
   */
  boolean hasToId();
  /**
   * <pre>
   * 传输人 、协同人，多个逗号隔开
   * </pre>
   *
   * <code>optional string toId = 1;</code>
   * @return The toId.
   */
  java.lang.String getToId();
  /**
   * <pre>
   * 传输人 、协同人，多个逗号隔开
   * </pre>
   *
   * <code>optional string toId = 1;</code>
   * @return The bytes for toId.
   */
  com.google.protobuf.ByteString
      getToIdBytes();

  /**
   * <pre>
   * 拦截、插入
   * </pre>
   *
   * <code>optional string fromId = 2;</code>
   * @return Whether the fromId field is set.
   */
  boolean hasFromId();
  /**
   * <pre>
   * 拦截、插入
   * </pre>
   *
   * <code>optional string fromId = 2;</code>
   * @return The fromId.
   */
  java.lang.String getFromId();
  /**
   * <pre>
   * 拦截、插入
   * </pre>
   *
   * <code>optional string fromId = 2;</code>
   * @return The bytes for fromId.
   */
  com.google.protobuf.ByteString
      getFromIdBytes();

  /**
   * <code>required string sessionId = 3;</code>
   * @return Whether the sessionId field is set.
   */
  boolean hasSessionId();
  /**
   * <code>required string sessionId = 3;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>required string sessionId = 3;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();
}
