// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kfMessage.proto

package com.ty.chat.protocol;

/**
 * Protobuf enum {@code protocol.MsgType}
 */
public enum MsgType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *文本
   * </pre>
   *
   * <code>MSG_TYPE_TEXT = 0;</code>
   */
  MSG_TYPE_TEXT(0),
  /**
   * <pre>
   *图片
   * </pre>
   *
   * <code>MSG_TYPE_IMG = 1;</code>
   */
  MSG_TYPE_IMG(1),
  /**
   * <pre>
   *语音
   * </pre>
   *
   * <code>MSG_TYPE_VOICE = 2;</code>
   */
  MSG_TYPE_VOICE(2),
  /**
   * <pre>
   *视频
   * </pre>
   *
   * <code>MSG_TYPE_VIDEO = 3;</code>
   */
  MSG_TYPE_VIDEO(3),
  /**
   * <pre>
   *音乐
   * </pre>
   *
   * <code>MSG_TYPE_MUSIC = 4;</code>
   */
  MSG_TYPE_MUSIC(4),
  /**
   * <pre>
   *图文
   * </pre>
   *
   * <code>MSG_TYPE_NEWS = 5;</code>
   */
  MSG_TYPE_NEWS(5),
  /**
   * <pre>
   *文件
   * </pre>
   *
   * <code>MSG_TYPE_File = 6;</code>
   */
  MSG_TYPE_File(6),
  /**
   * <pre>
   *文本预发
   * </pre>
   *
   * <code>MSG_TYPE_TEXT_ADVANCE = 7;</code>
   */
  MSG_TYPE_TEXT_ADVANCE(7),
  ;

  /**
   * <pre>
   *文本
   * </pre>
   *
   * <code>MSG_TYPE_TEXT = 0;</code>
   */
  public static final int MSG_TYPE_TEXT_VALUE = 0;
  /**
   * <pre>
   *图片
   * </pre>
   *
   * <code>MSG_TYPE_IMG = 1;</code>
   */
  public static final int MSG_TYPE_IMG_VALUE = 1;
  /**
   * <pre>
   *语音
   * </pre>
   *
   * <code>MSG_TYPE_VOICE = 2;</code>
   */
  public static final int MSG_TYPE_VOICE_VALUE = 2;
  /**
   * <pre>
   *视频
   * </pre>
   *
   * <code>MSG_TYPE_VIDEO = 3;</code>
   */
  public static final int MSG_TYPE_VIDEO_VALUE = 3;
  /**
   * <pre>
   *音乐
   * </pre>
   *
   * <code>MSG_TYPE_MUSIC = 4;</code>
   */
  public static final int MSG_TYPE_MUSIC_VALUE = 4;
  /**
   * <pre>
   *图文
   * </pre>
   *
   * <code>MSG_TYPE_NEWS = 5;</code>
   */
  public static final int MSG_TYPE_NEWS_VALUE = 5;
  /**
   * <pre>
   *文件
   * </pre>
   *
   * <code>MSG_TYPE_File = 6;</code>
   */
  public static final int MSG_TYPE_File_VALUE = 6;
  /**
   * <pre>
   *文本预发
   * </pre>
   *
   * <code>MSG_TYPE_TEXT_ADVANCE = 7;</code>
   */
  public static final int MSG_TYPE_TEXT_ADVANCE_VALUE = 7;


  public final int getNumber() {
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MsgType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MsgType forNumber(int value) {
    switch (value) {
      case 0: return MSG_TYPE_TEXT;
      case 1: return MSG_TYPE_IMG;
      case 2: return MSG_TYPE_VOICE;
      case 3: return MSG_TYPE_VIDEO;
      case 4: return MSG_TYPE_MUSIC;
      case 5: return MSG_TYPE_NEWS;
      case 6: return MSG_TYPE_File;
      case 7: return MSG_TYPE_TEXT_ADVANCE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MsgType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
          public MsgType findValueByNumber(int number) {
            return MsgType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.ty.chat.protocol.KfMessageOuterClass.getDescriptor().getEnumTypes().get(2);
  }

  private static final MsgType[] VALUES = values();

  public static MsgType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MsgType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:protocol.MsgType)
}

