// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kfMessage.proto

package com.ty.chat.protocol;

public interface ResponseResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.ResponseResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 code = 1;</code>
   * @return Whether the code field is set.
   */
  boolean hasCode();
  /**
   * <code>required int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>required string message = 2;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>required string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>required string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
