// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kfMessage.proto

package com.ty.chatlib.protocol;

public interface KfMessageRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.KfMessageResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string extras = 1;</code>
   * @return Whether the extras field is set.
   */
  boolean hasExtras();
  /**
   * <code>optional string extras = 1;</code>
   * @return The extras.
   */
  String getExtras();
  /**
   * <code>optional string extras = 1;</code>
   * @return The bytes for extras.
   */
  com.google.protobuf.ByteString
      getExtrasBytes();

  /**
   * <code>optional string content = 2;</code>
   * @return Whether the content field is set.
   */
  boolean hasContent();
  /**
   * <code>optional string content = 2;</code>
   * @return The content.
   */
  String getContent();
  /**
   * <code>optional string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
