// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kfMessage.proto

package com.ty.chatlib.protocol;

public final class KfMessageOuterClass {
  private KfMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_KfMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_KfMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_KfOnline_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_KfOnline_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_KfReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_KfReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_KfSend_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_KfSend_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_KfIsReaded_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_KfIsReaded_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_KfAckAndCancel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_KfAckAndCancel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_KfWithdraw_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_KfWithdraw_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_KfHeartbeat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_KfHeartbeat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_KfSession_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_KfSession_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_KfMessageResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_KfMessageResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_KfUnendMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_KfUnendMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_KfForwardMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_KfForwardMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ResponseResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_ResponseResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017kfMessage.proto\022\010protocol\"\337\003\n\tKfMessag" +
      "e\022\036\n\003cmd\030\001 \002(\0162\021.protocol.Command\022\026\n\007ver" +
      "sion\030\002 \001(\t:\0051.0.0\022\036\n\005kfReq\030\003 \001(\0132\017.proto" +
      "col.KfReq\022 \n\006kfSend\030\004 \001(\0132\020.protocol.KfS" +
      "end\022(\n\nkfIsReaded\030\005 \001(\0132\024.protocol.KfIsR" +
      "eaded\0220\n\016kfAckAndCancel\030\006 \001(\0132\030.protocol" +
      ".KfAckAndCancel\022(\n\nkfWithdraw\030\007 \001(\0132\024.pr" +
      "otocol.KfWithdraw\022*\n\013kfHeartbeat\030\010 \001(\0132\025" +
      ".protocol.KfHeartbeat\022&\n\tkfSession\030\t \001(\013" +
      "2\023.protocol.KfSession\022.\n\rkfMessageResp\030\n" +
      " \001(\0132\027.protocol.KfMessageResp\022(\n\nkfUnend" +
      "Msg\030\013 \001(\0132\024.protocol.KfUnendMsg\022$\n\010kfOnl" +
      "ine\030\014 \001(\0132\022.protocol.KfOnline\"d\n\010KfOnlin" +
      "e\022\016\n\006fromId\030\001 \002(\t\022\016\n\006appkey\030\002 \002(\t\022\030\n\020app" +
      "RequestSource\030\003 \002(\t\022\016\n\006appSig\030\004 \001(\t\022\016\n\006s" +
      "tatus\030\005 \001(\t\"\226\001\n\005KfReq\022\021\n\tserviceId\030\001 \001(\t" +
      "\022\016\n\006extras\030\002 \001(\t\022\021\n\tvisiterId\030\003 \002(\t\022(\n\nd" +
      "eviceType\030\004 \001(\0162\024.protocol.DeviceType\022\026\n" +
      "\016dialogueSource\030\005 \001(\t\022\025\n\rintelligentId\030\006" +
      " \001(\t\"\236\001\n\006KfSend\0221\n\007msgType\030\001 \001(\0162\021.proto" +
      "col.MsgType:\rMSG_TYPE_TEXT\022\021\n\ttimeStamp\030" +
      "\002 \001(\t\022\017\n\007content\030\003 \002(\t\022\016\n\006fromId\030\004 \002(\t\022\016" +
      "\n\006extras\030\005 \001(\t\022\021\n\tsessionId\030\006 \002(\t\022\n\n\002id\030" +
      "\007 \001(\005\",\n\nKfIsReaded\022\013\n\003ids\030\001 \002(\t\022\021\n\tsess" +
      "ionId\030\002 \002(\t\"/\n\016KfAckAndCancel\022\021\n\tsession" +
      "Id\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\"=\n\nKfWithdraw\022\014\n\004to" +
      "Id\030\001 \001(\t\022\016\n\006fromId\030\002 \001(\t\022\021\n\tsessionId\030\003 " +
      "\002(\t\"&\n\013KfHeartbeat\022\n\n\002id\030\001 \002(\005\022\013\n\003ack\030\002 " +
      "\002(\005\"\267\001\n\tKfSession\022\021\n\tsessionId\030\001 \002(\t\022\021\n\t" +
      "serviceId\030\002 \001(\t\022\021\n\tvisiterId\030\003 \001(\t\022\n\n\002ip" +
      "\030\004 \001(\t\022\017\n\007address\030\005 \001(\t\022\022\n\ndeviceType\030\006 " +
      "\001(\005\022\021\n\ttimeStamp\030\007 \001(\t\022\026\n\016dialogueSource" +
      "\030\010 \001(\t\022\025\n\rintelligentId\030\t \001(\t\"0\n\rKfMessa" +
      "geResp\022\016\n\006extras\030\001 \001(\t\022\017\n\007content\030\002 \001(\t\"" +
      "\312\001\n\nKfUnendMsg\0221\n\007msgType\030\001 \001(\0162\021.protoc" +
      "ol.MsgType:\rMSG_TYPE_TEXT\022\021\n\ttimeStamp\030\002" +
      " \001(\t\022\017\n\007content\030\003 \002(\t\022\016\n\006fromId\030\004 \002(\t\022\020\n" +
      "\006extras\030\005 \001(\t:\000\022\021\n\tsessionId\030\006 \002(\t\022\n\n\002id" +
      "\030\007 \001(\005\022\020\n\005isAck\030\010 \001(\005:\0010\022\022\n\007isReade\030\t \001(" +
      "\005:\0010\"\320\002\n\020KfForwardMessage\022\036\n\003cmd\030\001 \001(\0162\021" +
      ".protocol.Command\022\016\n\006appKey\030\002 \002(\t\022\014\n\004toI" +
      "d\030\003 \001(\t\022 \n\006kfSend\030\004 \001(\0132\020.protocol.KfSen" +
      "d\022(\n\nkfIsReaded\030\005 \001(\0132\024.protocol.KfIsRea" +
      "ded\0220\n\016kfAckAndCancel\030\006 \001(\0132\030.protocol.K" +
      "fAckAndCancel\022(\n\nkfWithdraw\030\007 \001(\0132\024.prot" +
      "ocol.KfWithdraw\022.\n\rkfMessageResp\030\010 \001(\0132\027" +
      ".protocol.KfMessageResp\022&\n\tkfSession\030\t \001" +
      "(\0132\023.protocol.KfSession\"/\n\016ResponseResul" +
      "t\022\014\n\004code\030\001 \002(\005\022\017\n\007message\030\002 \002(\t*f\n\nDevi" +
      "ceType\022\026\n\022DEVICE_TYPE_UNKNOW\020\000\022\022\n\016DEVICE" +
      "_TYPE_PC\020\001\022\027\n\023DEVICE_TYPE_ANDROID\020\002\022\023\n\017D" +
      "EVICE_TYPE_IOS\020\003*\245\005\n\007Command\022\022\n\016COMMAND_" +
      "UNKNOW\020\000\022\026\n\022COMMAND_ONLINE_REQ\020\001\022\027\n\023COMM" +
      "AND_ONLINE_RESP\020\002\022\034\n\030COMMAND_TRANSMISSIO" +
      "N_REQ\020\003\022\035\n\031COMMAND_TRANSMISSION_RESP\020\004\022\031" +
      "\n\025COMMAND_INTERCEPT_REQ\020\005\022\032\n\026COMMAND_INT" +
      "ERCEPT_RESP\020\006\022\026\n\022COMMAND_INSERT_REQ\020\007\022\027\n" +
      "\023COMMAND_INSERT_RESP\020\010\022\027\n\023COMMAND_SYNERG" +
      "Y_REQ\020\t\022\030\n\024COMMAND_SYNERGY_RESP\020\n\022\024\n\020COM" +
      "MAND_CHAT_REQ\020\013\022\025\n\021COMMAND_CHAT_RESP\020\014\022\025" +
      "\n\021COMMAND_CLOSE_REQ\020\r\022\026\n\022COMMAND_CLOSE_R" +
      "ESP\020\016\022\032\n\026COMMAND_CANCEL_MSG_REQ\020\017\022\033\n\027COM" +
      "MAND_CANCEL_MSG_RESP\020\020\022\035\n\031COMMAND_UNEND_" +
      "SESSION_MSG\020\021\022\032\n\026COMMAND_CREATE_SESSION\020" +
      "\022\022\034\n\030COMMAND_PUSH_NEW_SESSION\020\023\022\031\n\025COMMA" +
      "ND_HEARTBEAT_REQ\020\024\022\032\n\026COMMAND_PUSH_IS_RE" +
      "ADED\020\025\022\031\n\025COMMAND_PUSH_TO_QUEUE\020\026\022 \n\034COM" +
      "MAND_PUSH_PICK_UP_SESSION\020\027\022\033\n\027COMMAND_P" +
      "USH_TO_SESSION\020\030*\253\001\n\007MsgType\022\021\n\rMSG_TYPE" +
      "_TEXT\020\000\022\020\n\014MSG_TYPE_IMG\020\001\022\022\n\016MSG_TYPE_VO" +
      "ICE\020\002\022\022\n\016MSG_TYPE_VIDEO\020\003\022\022\n\016MSG_TYPE_MU" +
      "SIC\020\004\022\021\n\rMSG_TYPE_NEWS\020\005\022\021\n\rMSG_TYPE_Fil" +
      "e\020\006\022\031\n\025MSG_TYPE_TEXT_ADVANCE\020\007B\033\n\027com.ty" +
      ".chatlib.protocolP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_KfMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_KfMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_KfMessage_descriptor,
        new String[] { "Cmd", "Version", "KfReq", "KfSend", "KfIsReaded", "KfAckAndCancel", "KfWithdraw", "KfHeartbeat", "KfSession", "KfMessageResp", "KfUnendMsg", "KfOnline", });
    internal_static_protocol_KfOnline_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_KfOnline_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_KfOnline_descriptor,
        new String[] { "FromId", "Appkey", "AppRequestSource", "AppSig", "Status", });
    internal_static_protocol_KfReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_KfReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_KfReq_descriptor,
        new String[] { "ServiceId", "Extras", "VisiterId", "DeviceType", "DialogueSource", "IntelligentId", });
    internal_static_protocol_KfSend_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protocol_KfSend_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_KfSend_descriptor,
        new String[] { "MsgType", "TimeStamp", "Content", "FromId", "Extras", "SessionId", "Id", });
    internal_static_protocol_KfIsReaded_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_protocol_KfIsReaded_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_KfIsReaded_descriptor,
        new String[] { "Ids", "SessionId", });
    internal_static_protocol_KfAckAndCancel_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_protocol_KfAckAndCancel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_KfAckAndCancel_descriptor,
        new String[] { "SessionId", "Id", });
    internal_static_protocol_KfWithdraw_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_protocol_KfWithdraw_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_KfWithdraw_descriptor,
        new String[] { "ToId", "FromId", "SessionId", });
    internal_static_protocol_KfHeartbeat_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_protocol_KfHeartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_KfHeartbeat_descriptor,
        new String[] { "Id", "Ack", });
    internal_static_protocol_KfSession_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_protocol_KfSession_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_KfSession_descriptor,
        new String[] { "SessionId", "ServiceId", "VisiterId", "Ip", "Address", "DeviceType", "TimeStamp", "DialogueSource", "IntelligentId", });
    internal_static_protocol_KfMessageResp_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_protocol_KfMessageResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_KfMessageResp_descriptor,
        new String[] { "Extras", "Content", });
    internal_static_protocol_KfUnendMsg_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_protocol_KfUnendMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_KfUnendMsg_descriptor,
        new String[] { "MsgType", "TimeStamp", "Content", "FromId", "Extras", "SessionId", "Id", "IsAck", "IsReade", });
    internal_static_protocol_KfForwardMessage_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_protocol_KfForwardMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_KfForwardMessage_descriptor,
        new String[] { "Cmd", "AppKey", "ToId", "KfSend", "KfIsReaded", "KfAckAndCancel", "KfWithdraw", "KfMessageResp", "KfSession", });
    internal_static_protocol_ResponseResult_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_protocol_ResponseResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_ResponseResult_descriptor,
        new String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
