// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kfMessage.proto

package com.ty.chatlib.protocol;

/**
 * <pre>
 * 上线
 * </pre>
 *
 * Protobuf type {@code protocol.KfOnline}
 */
public  final class KfOnline extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.KfOnline)
    KfOnlineOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KfOnline.newBuilder() to construct.
  private KfOnline(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KfOnline() {
    fromId_ = "";
    appkey_ = "";
    appRequestSource_ = "";
    appSig_ = "";
    status_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new KfOnline();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private KfOnline(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            fromId_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            appkey_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            appRequestSource_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            appSig_ = bs;
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            status_ = bs;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ty.chatlib.protocol.KfMessageOuterClass.internal_static_protocol_KfOnline_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ty.chatlib.protocol.KfMessageOuterClass.internal_static_protocol_KfOnline_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            KfOnline.class, Builder.class);
  }

  private int bitField0_;
  public static final int FROMID_FIELD_NUMBER = 1;
  private volatile Object fromId_;
  /**
   * <code>required string fromId = 1;</code>
   * @return Whether the fromId field is set.
   */
  public boolean hasFromId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string fromId = 1;</code>
   * @return The fromId.
   */
  public String getFromId() {
    Object ref = fromId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        fromId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string fromId = 1;</code>
   * @return The bytes for fromId.
   */
  public com.google.protobuf.ByteString
      getFromIdBytes() {
    Object ref = fromId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      fromId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPKEY_FIELD_NUMBER = 2;
  private volatile Object appkey_;
  /**
   * <code>required string appkey = 2;</code>
   * @return Whether the appkey field is set.
   */
  public boolean hasAppkey() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string appkey = 2;</code>
   * @return The appkey.
   */
  public String getAppkey() {
    Object ref = appkey_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        appkey_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string appkey = 2;</code>
   * @return The bytes for appkey.
   */
  public com.google.protobuf.ByteString
      getAppkeyBytes() {
    Object ref = appkey_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      appkey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPREQUESTSOURCE_FIELD_NUMBER = 3;
  private volatile Object appRequestSource_;
  /**
   * <code>required string appRequestSource = 3;</code>
   * @return Whether the appRequestSource field is set.
   */
  public boolean hasAppRequestSource() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required string appRequestSource = 3;</code>
   * @return The appRequestSource.
   */
  public String getAppRequestSource() {
    Object ref = appRequestSource_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        appRequestSource_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string appRequestSource = 3;</code>
   * @return The bytes for appRequestSource.
   */
  public com.google.protobuf.ByteString
      getAppRequestSourceBytes() {
    Object ref = appRequestSource_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      appRequestSource_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPSIG_FIELD_NUMBER = 4;
  private volatile Object appSig_;
  /**
   * <code>optional string appSig = 4;</code>
   * @return Whether the appSig field is set.
   */
  public boolean hasAppSig() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string appSig = 4;</code>
   * @return The appSig.
   */
  public String getAppSig() {
    Object ref = appSig_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        appSig_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string appSig = 4;</code>
   * @return The bytes for appSig.
   */
  public com.google.protobuf.ByteString
      getAppSigBytes() {
    Object ref = appSig_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      appSig_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  private volatile Object status_;
  /**
   * <code>optional string status = 5;</code>
   * @return Whether the status field is set.
   */
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string status = 5;</code>
   * @return The status.
   */
  public String getStatus() {
    Object ref = status_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        status_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string status = 5;</code>
   * @return The bytes for status.
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    Object ref = status_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasFromId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasAppkey()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasAppRequestSource()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fromId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, appkey_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, appRequestSource_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, appSig_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, status_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fromId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, appkey_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, appRequestSource_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, appSig_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, status_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof KfOnline)) {
      return super.equals(obj);
    }
    KfOnline other = (KfOnline) obj;

    if (hasFromId() != other.hasFromId()) return false;
    if (hasFromId()) {
      if (!getFromId()
          .equals(other.getFromId())) return false;
    }
    if (hasAppkey() != other.hasAppkey()) return false;
    if (hasAppkey()) {
      if (!getAppkey()
          .equals(other.getAppkey())) return false;
    }
    if (hasAppRequestSource() != other.hasAppRequestSource()) return false;
    if (hasAppRequestSource()) {
      if (!getAppRequestSource()
          .equals(other.getAppRequestSource())) return false;
    }
    if (hasAppSig() != other.hasAppSig()) return false;
    if (hasAppSig()) {
      if (!getAppSig()
          .equals(other.getAppSig())) return false;
    }
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFromId()) {
      hash = (37 * hash) + FROMID_FIELD_NUMBER;
      hash = (53 * hash) + getFromId().hashCode();
    }
    if (hasAppkey()) {
      hash = (37 * hash) + APPKEY_FIELD_NUMBER;
      hash = (53 * hash) + getAppkey().hashCode();
    }
    if (hasAppRequestSource()) {
      hash = (37 * hash) + APPREQUESTSOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getAppRequestSource().hashCode();
    }
    if (hasAppSig()) {
      hash = (37 * hash) + APPSIG_FIELD_NUMBER;
      hash = (53 * hash) + getAppSig().hashCode();
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static KfOnline parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static KfOnline parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static KfOnline parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static KfOnline parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static KfOnline parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static KfOnline parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static KfOnline parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static KfOnline parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static KfOnline parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static KfOnline parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static KfOnline parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static KfOnline parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(KfOnline prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 上线
   * </pre>
   *
   * Protobuf type {@code protocol.KfOnline}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.KfOnline)
      com.ty.chatlib.protocol.KfOnlineOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ty.chatlib.protocol.KfMessageOuterClass.internal_static_protocol_KfOnline_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ty.chatlib.protocol.KfMessageOuterClass.internal_static_protocol_KfOnline_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              KfOnline.class, Builder.class);
    }

    // Construct using com.ty.chatlib.protocol.KfOnline.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      fromId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      appkey_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      appRequestSource_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      appSig_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      status_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ty.chatlib.protocol.KfMessageOuterClass.internal_static_protocol_KfOnline_descriptor;
    }

    @Override
    public KfOnline getDefaultInstanceForType() {
      return KfOnline.getDefaultInstance();
    }

    @Override
    public KfOnline build() {
      KfOnline result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public KfOnline buildPartial() {
      KfOnline result = new KfOnline(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.fromId_ = fromId_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.appkey_ = appkey_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.appRequestSource_ = appRequestSource_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.appSig_ = appSig_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.status_ = status_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof KfOnline) {
        return mergeFrom((KfOnline)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(KfOnline other) {
      if (other == KfOnline.getDefaultInstance()) return this;
      if (other.hasFromId()) {
        bitField0_ |= 0x00000001;
        fromId_ = other.fromId_;
        onChanged();
      }
      if (other.hasAppkey()) {
        bitField0_ |= 0x00000002;
        appkey_ = other.appkey_;
        onChanged();
      }
      if (other.hasAppRequestSource()) {
        bitField0_ |= 0x00000004;
        appRequestSource_ = other.appRequestSource_;
        onChanged();
      }
      if (other.hasAppSig()) {
        bitField0_ |= 0x00000008;
        appSig_ = other.appSig_;
        onChanged();
      }
      if (other.hasStatus()) {
        bitField0_ |= 0x00000010;
        status_ = other.status_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      if (!hasFromId()) {
        return false;
      }
      if (!hasAppkey()) {
        return false;
      }
      if (!hasAppRequestSource()) {
        return false;
      }
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      KfOnline parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (KfOnline) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object fromId_ = "";
    /**
     * <code>required string fromId = 1;</code>
     * @return Whether the fromId field is set.
     */
    public boolean hasFromId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string fromId = 1;</code>
     * @return The fromId.
     */
    public String getFromId() {
      Object ref = fromId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromId_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>required string fromId = 1;</code>
     * @return The bytes for fromId.
     */
    public com.google.protobuf.ByteString
        getFromIdBytes() {
      Object ref = fromId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string fromId = 1;</code>
     * @param value The fromId to set.
     * @return This builder for chaining.
     */
    public Builder setFromId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      fromId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string fromId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      fromId_ = getDefaultInstance().getFromId();
      onChanged();
      return this;
    }
    /**
     * <code>required string fromId = 1;</code>
     * @param value The bytes for fromId to set.
     * @return This builder for chaining.
     */
    public Builder setFromIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      fromId_ = value;
      onChanged();
      return this;
    }

    private Object appkey_ = "";
    /**
     * <code>required string appkey = 2;</code>
     * @return Whether the appkey field is set.
     */
    public boolean hasAppkey() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string appkey = 2;</code>
     * @return The appkey.
     */
    public String getAppkey() {
      Object ref = appkey_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appkey_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>required string appkey = 2;</code>
     * @return The bytes for appkey.
     */
    public com.google.protobuf.ByteString
        getAppkeyBytes() {
      Object ref = appkey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        appkey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string appkey = 2;</code>
     * @param value The appkey to set.
     * @return This builder for chaining.
     */
    public Builder setAppkey(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      appkey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string appkey = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppkey() {
      bitField0_ = (bitField0_ & ~0x00000002);
      appkey_ = getDefaultInstance().getAppkey();
      onChanged();
      return this;
    }
    /**
     * <code>required string appkey = 2;</code>
     * @param value The bytes for appkey to set.
     * @return This builder for chaining.
     */
    public Builder setAppkeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      appkey_ = value;
      onChanged();
      return this;
    }

    private Object appRequestSource_ = "";
    /**
     * <code>required string appRequestSource = 3;</code>
     * @return Whether the appRequestSource field is set.
     */
    public boolean hasAppRequestSource() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string appRequestSource = 3;</code>
     * @return The appRequestSource.
     */
    public String getAppRequestSource() {
      Object ref = appRequestSource_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appRequestSource_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>required string appRequestSource = 3;</code>
     * @return The bytes for appRequestSource.
     */
    public com.google.protobuf.ByteString
        getAppRequestSourceBytes() {
      Object ref = appRequestSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        appRequestSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string appRequestSource = 3;</code>
     * @param value The appRequestSource to set.
     * @return This builder for chaining.
     */
    public Builder setAppRequestSource(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      appRequestSource_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string appRequestSource = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppRequestSource() {
      bitField0_ = (bitField0_ & ~0x00000004);
      appRequestSource_ = getDefaultInstance().getAppRequestSource();
      onChanged();
      return this;
    }
    /**
     * <code>required string appRequestSource = 3;</code>
     * @param value The bytes for appRequestSource to set.
     * @return This builder for chaining.
     */
    public Builder setAppRequestSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      appRequestSource_ = value;
      onChanged();
      return this;
    }

    private Object appSig_ = "";
    /**
     * <code>optional string appSig = 4;</code>
     * @return Whether the appSig field is set.
     */
    public boolean hasAppSig() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string appSig = 4;</code>
     * @return The appSig.
     */
    public String getAppSig() {
      Object ref = appSig_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appSig_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string appSig = 4;</code>
     * @return The bytes for appSig.
     */
    public com.google.protobuf.ByteString
        getAppSigBytes() {
      Object ref = appSig_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        appSig_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string appSig = 4;</code>
     * @param value The appSig to set.
     * @return This builder for chaining.
     */
    public Builder setAppSig(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      appSig_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string appSig = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppSig() {
      bitField0_ = (bitField0_ & ~0x00000008);
      appSig_ = getDefaultInstance().getAppSig();
      onChanged();
      return this;
    }
    /**
     * <code>optional string appSig = 4;</code>
     * @param value The bytes for appSig to set.
     * @return This builder for chaining.
     */
    public Builder setAppSigBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      appSig_ = value;
      onChanged();
      return this;
    }

    private Object status_ = "";
    /**
     * <code>optional string status = 5;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string status = 5;</code>
     * @return The status.
     */
    public String getStatus() {
      Object ref = status_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          status_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string status = 5;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string status = 5;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string status = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000010);
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>optional string status = 5;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      status_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.KfOnline)
  }

  // @@protoc_insertion_point(class_scope:protocol.KfOnline)
  private static final KfOnline DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new KfOnline();
  }

  public static KfOnline getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @Deprecated public static final com.google.protobuf.Parser<KfOnline>
      PARSER = new com.google.protobuf.AbstractParser<KfOnline>() {
    @Override
    public KfOnline parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new KfOnline(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<KfOnline> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<KfOnline> getParserForType() {
    return PARSER;
  }

  @Override
  public KfOnline getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

