// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kfMessage.proto

package com.ty.chatlib.protocol;

public interface KfReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.KfReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string serviceId = 1;</code>
   * @return Whether the serviceId field is set.
   */
  boolean hasServiceId();
  /**
   * <code>optional string serviceId = 1;</code>
   * @return The serviceId.
   */
  String getServiceId();
  /**
   * <code>optional string serviceId = 1;</code>
   * @return The bytes for serviceId.
   */
  com.google.protobuf.ByteString
      getServiceIdBytes();

  /**
   * <code>optional string extras = 2;</code>
   * @return Whether the extras field is set.
   */
  boolean hasExtras();
  /**
   * <code>optional string extras = 2;</code>
   * @return The extras.
   */
  String getExtras();
  /**
   * <code>optional string extras = 2;</code>
   * @return The bytes for extras.
   */
  com.google.protobuf.ByteString
      getExtrasBytes();

  /**
   * <code>required string visiterId = 3;</code>
   * @return Whether the visiterId field is set.
   */
  boolean hasVisiterId();
  /**
   * <code>required string visiterId = 3;</code>
   * @return The visiterId.
   */
  String getVisiterId();
  /**
   * <code>required string visiterId = 3;</code>
   * @return The bytes for visiterId.
   */
  com.google.protobuf.ByteString
      getVisiterIdBytes();

  /**
   * <code>optional .protocol.DeviceType deviceType = 4;</code>
   * @return Whether the deviceType field is set.
   */
  boolean hasDeviceType();
  /**
   * <code>optional .protocol.DeviceType deviceType = 4;</code>
   * @return The deviceType.
   */
  DeviceType getDeviceType();

  /**
   * <code>optional string dialogueSource = 5;</code>
   * @return Whether the dialogueSource field is set.
   */
  boolean hasDialogueSource();
  /**
   * <code>optional string dialogueSource = 5;</code>
   * @return The dialogueSource.
   */
  String getDialogueSource();
  /**
   * <code>optional string dialogueSource = 5;</code>
   * @return The bytes for dialogueSource.
   */
  com.google.protobuf.ByteString
      getDialogueSourceBytes();

  /**
   * <code>optional string intelligentId = 6;</code>
   * @return Whether the intelligentId field is set.
   */
  boolean hasIntelligentId();
  /**
   * <code>optional string intelligentId = 6;</code>
   * @return The intelligentId.
   */
  String getIntelligentId();
  /**
   * <code>optional string intelligentId = 6;</code>
   * @return The bytes for intelligentId.
   */
  com.google.protobuf.ByteString
      getIntelligentIdBytes();
}
