// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kfMessage.proto

package com.ty.chatlib.protocol;

/**
 * <pre>
 * 建立会话  // 14、18
 * </pre>
 *
 * Protobuf type {@code protocol.KfReq}
 */
public  final class KfReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.KfReq)
    KfReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KfReq.newBuilder() to construct.
  private KfReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KfReq() {
    serviceId_ = "";
    extras_ = "";
    visiterId_ = "";
    deviceType_ = 0;
    dialogueSource_ = "";
    intelligentId_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new KfReq();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private KfReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            serviceId_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            extras_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            visiterId_ = bs;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            com.ty.chatlib.protocol.DeviceType value = com.ty.chatlib.protocol.DeviceType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(4, rawValue);
            } else {
              bitField0_ |= 0x00000008;
              deviceType_ = rawValue;
            }
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            dialogueSource_ = bs;
            break;
          }
          case 50: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000020;
            intelligentId_ = bs;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ty.chatlib.protocol.KfMessageOuterClass.internal_static_protocol_KfReq_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ty.chatlib.protocol.KfMessageOuterClass.internal_static_protocol_KfReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            KfReq.class, Builder.class);
  }

  private int bitField0_;
  public static final int SERVICEID_FIELD_NUMBER = 1;
  private volatile Object serviceId_;
  /**
   * <code>optional string serviceId = 1;</code>
   * @return Whether the serviceId field is set.
   */
  public boolean hasServiceId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string serviceId = 1;</code>
   * @return The serviceId.
   */
  public String getServiceId() {
    Object ref = serviceId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        serviceId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string serviceId = 1;</code>
   * @return The bytes for serviceId.
   */
  public com.google.protobuf.ByteString
      getServiceIdBytes() {
    Object ref = serviceId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      serviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTRAS_FIELD_NUMBER = 2;
  private volatile Object extras_;
  /**
   * <code>optional string extras = 2;</code>
   * @return Whether the extras field is set.
   */
  public boolean hasExtras() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string extras = 2;</code>
   * @return The extras.
   */
  public String getExtras() {
    Object ref = extras_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        extras_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string extras = 2;</code>
   * @return The bytes for extras.
   */
  public com.google.protobuf.ByteString
      getExtrasBytes() {
    Object ref = extras_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      extras_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VISITERID_FIELD_NUMBER = 3;
  private volatile Object visiterId_;
  /**
   * <code>required string visiterId = 3;</code>
   * @return Whether the visiterId field is set.
   */
  public boolean hasVisiterId() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required string visiterId = 3;</code>
   * @return The visiterId.
   */
  public String getVisiterId() {
    Object ref = visiterId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        visiterId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string visiterId = 3;</code>
   * @return The bytes for visiterId.
   */
  public com.google.protobuf.ByteString
      getVisiterIdBytes() {
    Object ref = visiterId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      visiterId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICETYPE_FIELD_NUMBER = 4;
  private int deviceType_;
  /**
   * <code>optional .protocol.DeviceType deviceType = 4;</code>
   * @return Whether the deviceType field is set.
   */
  public boolean hasDeviceType() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .protocol.DeviceType deviceType = 4;</code>
   * @return The deviceType.
   */
  public com.ty.chatlib.protocol.DeviceType getDeviceType() {
    @SuppressWarnings("deprecation")
    com.ty.chatlib.protocol.DeviceType result = com.ty.chatlib.protocol.DeviceType.valueOf(deviceType_);
    return result == null ? com.ty.chatlib.protocol.DeviceType.DEVICE_TYPE_UNKNOW : result;
  }

  public static final int DIALOGUESOURCE_FIELD_NUMBER = 5;
  private volatile Object dialogueSource_;
  /**
   * <code>optional string dialogueSource = 5;</code>
   * @return Whether the dialogueSource field is set.
   */
  public boolean hasDialogueSource() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string dialogueSource = 5;</code>
   * @return The dialogueSource.
   */
  public String getDialogueSource() {
    Object ref = dialogueSource_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        dialogueSource_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string dialogueSource = 5;</code>
   * @return The bytes for dialogueSource.
   */
  public com.google.protobuf.ByteString
      getDialogueSourceBytes() {
    Object ref = dialogueSource_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dialogueSource_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTELLIGENTID_FIELD_NUMBER = 6;
  private volatile Object intelligentId_;
  /**
   * <code>optional string intelligentId = 6;</code>
   * @return Whether the intelligentId field is set.
   */
  public boolean hasIntelligentId() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string intelligentId = 6;</code>
   * @return The intelligentId.
   */
  public String getIntelligentId() {
    Object ref = intelligentId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        intelligentId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string intelligentId = 6;</code>
   * @return The bytes for intelligentId.
   */
  public com.google.protobuf.ByteString
      getIntelligentIdBytes() {
    Object ref = intelligentId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      intelligentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasVisiterId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serviceId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, extras_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, visiterId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeEnum(4, deviceType_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dialogueSource_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, intelligentId_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serviceId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, extras_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, visiterId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, deviceType_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dialogueSource_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, intelligentId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof KfReq)) {
      return super.equals(obj);
    }
    KfReq other = (KfReq) obj;

    if (hasServiceId() != other.hasServiceId()) return false;
    if (hasServiceId()) {
      if (!getServiceId()
          .equals(other.getServiceId())) return false;
    }
    if (hasExtras() != other.hasExtras()) return false;
    if (hasExtras()) {
      if (!getExtras()
          .equals(other.getExtras())) return false;
    }
    if (hasVisiterId() != other.hasVisiterId()) return false;
    if (hasVisiterId()) {
      if (!getVisiterId()
          .equals(other.getVisiterId())) return false;
    }
    if (hasDeviceType() != other.hasDeviceType()) return false;
    if (hasDeviceType()) {
      if (deviceType_ != other.deviceType_) return false;
    }
    if (hasDialogueSource() != other.hasDialogueSource()) return false;
    if (hasDialogueSource()) {
      if (!getDialogueSource()
          .equals(other.getDialogueSource())) return false;
    }
    if (hasIntelligentId() != other.hasIntelligentId()) return false;
    if (hasIntelligentId()) {
      if (!getIntelligentId()
          .equals(other.getIntelligentId())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasServiceId()) {
      hash = (37 * hash) + SERVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getServiceId().hashCode();
    }
    if (hasExtras()) {
      hash = (37 * hash) + EXTRAS_FIELD_NUMBER;
      hash = (53 * hash) + getExtras().hashCode();
    }
    if (hasVisiterId()) {
      hash = (37 * hash) + VISITERID_FIELD_NUMBER;
      hash = (53 * hash) + getVisiterId().hashCode();
    }
    if (hasDeviceType()) {
      hash = (37 * hash) + DEVICETYPE_FIELD_NUMBER;
      hash = (53 * hash) + deviceType_;
    }
    if (hasDialogueSource()) {
      hash = (37 * hash) + DIALOGUESOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getDialogueSource().hashCode();
    }
    if (hasIntelligentId()) {
      hash = (37 * hash) + INTELLIGENTID_FIELD_NUMBER;
      hash = (53 * hash) + getIntelligentId().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static KfReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static KfReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static KfReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static KfReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static KfReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static KfReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static KfReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static KfReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static KfReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static KfReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static KfReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static KfReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(KfReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 建立会话  // 14、18
   * </pre>
   *
   * Protobuf type {@code protocol.KfReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.KfReq)
      com.ty.chatlib.protocol.KfReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ty.chatlib.protocol.KfMessageOuterClass.internal_static_protocol_KfReq_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ty.chatlib.protocol.KfMessageOuterClass.internal_static_protocol_KfReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              KfReq.class, Builder.class);
    }

    // Construct using com.ty.chatlib.protocol.KfReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      serviceId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      extras_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      visiterId_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      deviceType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      dialogueSource_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      intelligentId_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ty.chatlib.protocol.KfMessageOuterClass.internal_static_protocol_KfReq_descriptor;
    }

    @Override
    public KfReq getDefaultInstanceForType() {
      return KfReq.getDefaultInstance();
    }

    @Override
    public KfReq build() {
      KfReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public KfReq buildPartial() {
      KfReq result = new KfReq(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.serviceId_ = serviceId_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.extras_ = extras_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.visiterId_ = visiterId_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.deviceType_ = deviceType_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.dialogueSource_ = dialogueSource_;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        to_bitField0_ |= 0x00000020;
      }
      result.intelligentId_ = intelligentId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof KfReq) {
        return mergeFrom((KfReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(KfReq other) {
      if (other == KfReq.getDefaultInstance()) return this;
      if (other.hasServiceId()) {
        bitField0_ |= 0x00000001;
        serviceId_ = other.serviceId_;
        onChanged();
      }
      if (other.hasExtras()) {
        bitField0_ |= 0x00000002;
        extras_ = other.extras_;
        onChanged();
      }
      if (other.hasVisiterId()) {
        bitField0_ |= 0x00000004;
        visiterId_ = other.visiterId_;
        onChanged();
      }
      if (other.hasDeviceType()) {
        setDeviceType(other.getDeviceType());
      }
      if (other.hasDialogueSource()) {
        bitField0_ |= 0x00000010;
        dialogueSource_ = other.dialogueSource_;
        onChanged();
      }
      if (other.hasIntelligentId()) {
        bitField0_ |= 0x00000020;
        intelligentId_ = other.intelligentId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      if (!hasVisiterId()) {
        return false;
      }
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      KfReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (KfReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object serviceId_ = "";
    /**
     * <code>optional string serviceId = 1;</code>
     * @return Whether the serviceId field is set.
     */
    public boolean hasServiceId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string serviceId = 1;</code>
     * @return The serviceId.
     */
    public String getServiceId() {
      Object ref = serviceId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceId_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string serviceId = 1;</code>
     * @return The bytes for serviceId.
     */
    public com.google.protobuf.ByteString
        getServiceIdBytes() {
      Object ref = serviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string serviceId = 1;</code>
     * @param value The serviceId to set.
     * @return This builder for chaining.
     */
    public Builder setServiceId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      serviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string serviceId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      serviceId_ = getDefaultInstance().getServiceId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string serviceId = 1;</code>
     * @param value The bytes for serviceId to set.
     * @return This builder for chaining.
     */
    public Builder setServiceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      serviceId_ = value;
      onChanged();
      return this;
    }

    private Object extras_ = "";
    /**
     * <code>optional string extras = 2;</code>
     * @return Whether the extras field is set.
     */
    public boolean hasExtras() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string extras = 2;</code>
     * @return The extras.
     */
    public String getExtras() {
      Object ref = extras_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          extras_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string extras = 2;</code>
     * @return The bytes for extras.
     */
    public com.google.protobuf.ByteString
        getExtrasBytes() {
      Object ref = extras_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        extras_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string extras = 2;</code>
     * @param value The extras to set.
     * @return This builder for chaining.
     */
    public Builder setExtras(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      extras_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string extras = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtras() {
      bitField0_ = (bitField0_ & ~0x00000002);
      extras_ = getDefaultInstance().getExtras();
      onChanged();
      return this;
    }
    /**
     * <code>optional string extras = 2;</code>
     * @param value The bytes for extras to set.
     * @return This builder for chaining.
     */
    public Builder setExtrasBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      extras_ = value;
      onChanged();
      return this;
    }

    private Object visiterId_ = "";
    /**
     * <code>required string visiterId = 3;</code>
     * @return Whether the visiterId field is set.
     */
    public boolean hasVisiterId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string visiterId = 3;</code>
     * @return The visiterId.
     */
    public String getVisiterId() {
      Object ref = visiterId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          visiterId_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>required string visiterId = 3;</code>
     * @return The bytes for visiterId.
     */
    public com.google.protobuf.ByteString
        getVisiterIdBytes() {
      Object ref = visiterId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        visiterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string visiterId = 3;</code>
     * @param value The visiterId to set.
     * @return This builder for chaining.
     */
    public Builder setVisiterId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      visiterId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string visiterId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearVisiterId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      visiterId_ = getDefaultInstance().getVisiterId();
      onChanged();
      return this;
    }
    /**
     * <code>required string visiterId = 3;</code>
     * @param value The bytes for visiterId to set.
     * @return This builder for chaining.
     */
    public Builder setVisiterIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      visiterId_ = value;
      onChanged();
      return this;
    }

    private int deviceType_ = 0;
    /**
     * <code>optional .protocol.DeviceType deviceType = 4;</code>
     * @return Whether the deviceType field is set.
     */
    public boolean hasDeviceType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .protocol.DeviceType deviceType = 4;</code>
     * @return The deviceType.
     */
    public com.ty.chatlib.protocol.DeviceType getDeviceType() {
      @SuppressWarnings("deprecation")
      com.ty.chatlib.protocol.DeviceType result = com.ty.chatlib.protocol.DeviceType.valueOf(deviceType_);
      return result == null ? com.ty.chatlib.protocol.DeviceType.DEVICE_TYPE_UNKNOW : result;
    }
    /**
     * <code>optional .protocol.DeviceType deviceType = 4;</code>
     * @param value The deviceType to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceType(com.ty.chatlib.protocol.DeviceType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      deviceType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .protocol.DeviceType deviceType = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      deviceType_ = 0;
      onChanged();
      return this;
    }

    private Object dialogueSource_ = "";
    /**
     * <code>optional string dialogueSource = 5;</code>
     * @return Whether the dialogueSource field is set.
     */
    public boolean hasDialogueSource() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string dialogueSource = 5;</code>
     * @return The dialogueSource.
     */
    public String getDialogueSource() {
      Object ref = dialogueSource_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dialogueSource_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string dialogueSource = 5;</code>
     * @return The bytes for dialogueSource.
     */
    public com.google.protobuf.ByteString
        getDialogueSourceBytes() {
      Object ref = dialogueSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dialogueSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string dialogueSource = 5;</code>
     * @param value The dialogueSource to set.
     * @return This builder for chaining.
     */
    public Builder setDialogueSource(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      dialogueSource_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string dialogueSource = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDialogueSource() {
      bitField0_ = (bitField0_ & ~0x00000010);
      dialogueSource_ = getDefaultInstance().getDialogueSource();
      onChanged();
      return this;
    }
    /**
     * <code>optional string dialogueSource = 5;</code>
     * @param value The bytes for dialogueSource to set.
     * @return This builder for chaining.
     */
    public Builder setDialogueSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      dialogueSource_ = value;
      onChanged();
      return this;
    }

    private Object intelligentId_ = "";
    /**
     * <code>optional string intelligentId = 6;</code>
     * @return Whether the intelligentId field is set.
     */
    public boolean hasIntelligentId() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string intelligentId = 6;</code>
     * @return The intelligentId.
     */
    public String getIntelligentId() {
      Object ref = intelligentId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          intelligentId_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string intelligentId = 6;</code>
     * @return The bytes for intelligentId.
     */
    public com.google.protobuf.ByteString
        getIntelligentIdBytes() {
      Object ref = intelligentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        intelligentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string intelligentId = 6;</code>
     * @param value The intelligentId to set.
     * @return This builder for chaining.
     */
    public Builder setIntelligentId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      intelligentId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string intelligentId = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearIntelligentId() {
      bitField0_ = (bitField0_ & ~0x00000020);
      intelligentId_ = getDefaultInstance().getIntelligentId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string intelligentId = 6;</code>
     * @param value The bytes for intelligentId to set.
     * @return This builder for chaining.
     */
    public Builder setIntelligentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      intelligentId_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.KfReq)
  }

  // @@protoc_insertion_point(class_scope:protocol.KfReq)
  private static final KfReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new KfReq();
  }

  public static KfReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @Deprecated public static final com.google.protobuf.Parser<KfReq>
      PARSER = new com.google.protobuf.AbstractParser<KfReq>() {
    @Override
    public KfReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new KfReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<KfReq> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<KfReq> getParserForType() {
    return PARSER;
  }

  @Override
  public KfReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

