// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kfMessage.proto

package com.ty.chatlib.protocol;

public interface KfSessionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.KfSession)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string sessionId = 1;</code>
   * @return Whether the sessionId field is set.
   */
  boolean hasSessionId();
  /**
   * <code>required string sessionId = 1;</code>
   * @return The sessionId.
   */
  String getSessionId();
  /**
   * <code>required string sessionId = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>optional string serviceId = 2;</code>
   * @return Whether the serviceId field is set.
   */
  boolean hasServiceId();
  /**
   * <code>optional string serviceId = 2;</code>
   * @return The serviceId.
   */
  String getServiceId();
  /**
   * <code>optional string serviceId = 2;</code>
   * @return The bytes for serviceId.
   */
  com.google.protobuf.ByteString
      getServiceIdBytes();

  /**
   * <code>optional string visiterId = 3;</code>
   * @return Whether the visiterId field is set.
   */
  boolean hasVisiterId();
  /**
   * <code>optional string visiterId = 3;</code>
   * @return The visiterId.
   */
  String getVisiterId();
  /**
   * <code>optional string visiterId = 3;</code>
   * @return The bytes for visiterId.
   */
  com.google.protobuf.ByteString
      getVisiterIdBytes();

  /**
   * <code>optional string ip = 4;</code>
   * @return Whether the ip field is set.
   */
  boolean hasIp();
  /**
   * <code>optional string ip = 4;</code>
   * @return The ip.
   */
  String getIp();
  /**
   * <code>optional string ip = 4;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>optional string address = 5;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>optional string address = 5;</code>
   * @return The address.
   */
  String getAddress();
  /**
   * <code>optional string address = 5;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>optional int32 deviceType = 6;</code>
   * @return Whether the deviceType field is set.
   */
  boolean hasDeviceType();
  /**
   * <code>optional int32 deviceType = 6;</code>
   * @return The deviceType.
   */
  int getDeviceType();

  /**
   * <code>optional string timeStamp = 7;</code>
   * @return Whether the timeStamp field is set.
   */
  boolean hasTimeStamp();
  /**
   * <code>optional string timeStamp = 7;</code>
   * @return The timeStamp.
   */
  String getTimeStamp();
  /**
   * <code>optional string timeStamp = 7;</code>
   * @return The bytes for timeStamp.
   */
  com.google.protobuf.ByteString
      getTimeStampBytes();

  /**
   * <code>optional string dialogueSource = 8;</code>
   * @return Whether the dialogueSource field is set.
   */
  boolean hasDialogueSource();
  /**
   * <code>optional string dialogueSource = 8;</code>
   * @return The dialogueSource.
   */
  String getDialogueSource();
  /**
   * <code>optional string dialogueSource = 8;</code>
   * @return The bytes for dialogueSource.
   */
  com.google.protobuf.ByteString
      getDialogueSourceBytes();

  /**
   * <code>optional string intelligentId = 9;</code>
   * @return Whether the intelligentId field is set.
   */
  boolean hasIntelligentId();
  /**
   * <code>optional string intelligentId = 9;</code>
   * @return The intelligentId.
   */
  String getIntelligentId();
  /**
   * <code>optional string intelligentId = 9;</code>
   * @return The bytes for intelligentId.
   */
  com.google.protobuf.ByteString
      getIntelligentIdBytes();
}
