// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kfMessage.proto

package com.ty.chatlib.protocol;

public interface KfUnendMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.KfUnendMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .protocol.MsgType msgType = 1 [default = MSG_TYPE_TEXT];</code>
   * @return Whether the msgType field is set.
   */
  boolean hasMsgType();
  /**
   * <code>optional .protocol.MsgType msgType = 1 [default = MSG_TYPE_TEXT];</code>
   * @return The msgType.
   */
  MsgType getMsgType();

  /**
   * <code>optional string timeStamp = 2;</code>
   * @return Whether the timeStamp field is set.
   */
  boolean hasTimeStamp();
  /**
   * <code>optional string timeStamp = 2;</code>
   * @return The timeStamp.
   */
  String getTimeStamp();
  /**
   * <code>optional string timeStamp = 2;</code>
   * @return The bytes for timeStamp.
   */
  com.google.protobuf.ByteString
      getTimeStampBytes();

  /**
   * <code>required string content = 3;</code>
   * @return Whether the content field is set.
   */
  boolean hasContent();
  /**
   * <code>required string content = 3;</code>
   * @return The content.
   */
  String getContent();
  /**
   * <code>required string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>required string fromId = 4;</code>
   * @return Whether the fromId field is set.
   */
  boolean hasFromId();
  /**
   * <code>required string fromId = 4;</code>
   * @return The fromId.
   */
  String getFromId();
  /**
   * <code>required string fromId = 4;</code>
   * @return The bytes for fromId.
   */
  com.google.protobuf.ByteString
      getFromIdBytes();

  /**
   * <code>optional string extras = 5 [default = ""];</code>
   * @return Whether the extras field is set.
   */
  boolean hasExtras();
  /**
   * <code>optional string extras = 5 [default = ""];</code>
   * @return The extras.
   */
  String getExtras();
  /**
   * <code>optional string extras = 5 [default = ""];</code>
   * @return The bytes for extras.
   */
  com.google.protobuf.ByteString
      getExtrasBytes();

  /**
   * <code>required string sessionId = 6;</code>
   * @return Whether the sessionId field is set.
   */
  boolean hasSessionId();
  /**
   * <code>required string sessionId = 6;</code>
   * @return The sessionId.
   */
  String getSessionId();
  /**
   * <code>required string sessionId = 6;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>optional int32 id = 7;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional int32 id = 7;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>optional int32 isAck = 8 [default = 0];</code>
   * @return Whether the isAck field is set.
   */
  boolean hasIsAck();
  /**
   * <code>optional int32 isAck = 8 [default = 0];</code>
   * @return The isAck.
   */
  int getIsAck();

  /**
   * <code>optional int32 isReade = 9 [default = 0];</code>
   * @return Whether the isReade field is set.
   */
  boolean hasIsReade();
  /**
   * <code>optional int32 isReade = 9 [default = 0];</code>
   * @return The isReade.
   */
  int getIsReade();
}
